// constants/permissions.js
export const PERMISSIONS = {
  // Core Transaction Permissions
  DRAWER: {
    VIEW: 'VIEW_DRAWER',
    MANAGE: 'MANAGE_DRAWER',
    RECONCILE: 'RECONCILE_DRAWER'
  },

  // Customer Management
  CUSTOMER: {
    CREATE: 'CREATE_CUSTOMER',
    VIEW: 'VIEW_CUSTOMER',
    UPDATE: 'UPDATE_CUSTOMER',
    DELETE: 'DELETE_CUSTOMER',
    KYC_VERIFY: 'VERIFY_KYC'
  },

  // Account Operations
  ACCOUNT: {
    OPEN: 'OPEN_ACCOUNT',
    CLOSE: 'CLOSE_ACCOUNT',
    FREEZE: 'FREEZE_ACCOUNT',
    VIEW_BALANCE: 'VIEW_ACCOUNT_BALANCE',
    VIEW_STATEMENT: 'VIEW_ACCOUNT_STATEMENT'
  },

  // Loan Operations
  LOAN_FEE: {
    CREATE: 'CREATE_LOAN_FEE',
    VIEW: 'VIEW_LOAN_FEES',
    UPDATE: 'UPDATE_LOAN_FEE',
    TOGGLE_STATUS: 'TOGGLE_LOAN_FEE_STATUS',
    WAIVE: 'WAIVE_LOAN_FEE'
  },

  LOAN_OPERATIONS: {
    DISBURSE: 'DISBURSE_LOAN',
    APPROVE: 'APPROVE_LOAN',
    REJECT: 'REJECT_LOAN',
    RESTRUCTURE: 'RESTRUCTURE_LOAN',
    WRITE_OFF: 'WRITE_OFF_LOAN',
    COLLECT: 'COLLECT_LOAN'
  },

  // Financial Posting
  POSTING: {
    CUSTOMER_POSTING: 'CUSTOMER_POSTING',
    GL_POSTING: 'GL_POSTING',
    REVERSE: 'REVERSE_TRANSACTION',
    ADJUST: 'ADJUST_TRANSACTION'
  },

  // Reports
  REPORT: {
    GENERATE: 'GENERATE_REPORTS',
    VIEW: 'VIEW_REPORTS',
    EXPORT: 'EXPORT_REPORTS',
    CUSTOM: 'CREATE_CUSTOM_REPORTS'
  },

  // System Administration
  SYSTEM_ADMIN: {
    MANAGE_USERS: 'MANAGE_USERS',
    AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
    SYSTEM_CONFIG: 'MANAGE_SYSTEM_CONFIG',
    BACKUP: 'SYSTEM_BACKUP',
    RESTORE: 'SYSTEM_RESTORE'
  },

  // Permission Management
  PERMISSION_MANAGEMENT: {
    CREATE_PERMISSION: 'CREATE_PERMISSION',
    VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
    UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',
    ASSIGN_ROLES: 'ASSIGN_ROLES',
    CLONE_ROLES: 'CLONE_ROLE_PERMISSIONS'
  },

  // Dashboard Access
  DASHBOARD: {
    VIEW: 'VIEW_DASHBOARD',
    CUSTOMIZE: 'CUSTOMIZE_DASHBOARD',
    SHARE: 'SHARE_DASHBOARD'
  },

  // Credit Application
  CREDIT_APPL: {
    CREATE: 'CREATE_CREDIT_APP',
    REVIEW: 'REVIEW_CREDIT_APP',
    APPROVE: 'APPROVE_CREDIT_APP',
    REJECT: 'REJECT_CREDIT_APP'
  },

  // Fixed Assets
  FIXED_ASSET: {
    REGISTER: 'REGISTER_ASSET',
    DEPRECIATE: 'CALC_DEPRECIATION',
    DISPOSE: 'DISPOSE_ASSET',
    TRANSFER: 'TRANSFER_ASSET'
  },
  APPROVAL: {
    FINANCIAL: 'APPROVE_FINANCIAL',
    TRANSACTION: 'APPROVE_TRANSACTION',
    CUSTOMER_RELATED: 'APPROVE_CUSTOMER_ACTION',
    LOAN: 'APPROVE_LOAN'
  },
   TREASURY: {
    VIEW: 'TREASURY_VIEW',
    MANAGE: 'TREASURY_MANAGE',
    APPROVE: 'TREASURY_APPROVE',
    // ... other treasury permissions ...
  },
  OPERATIONS: {
    VIEW: 'OPERATIONS_VIEW',
    MANAGE: 'OPERATIONS_MANAGE',
    APPROVE: 'OPERATIONS_APPROVE',
    // Add other operations-related permissions as needed
  },
  // Add this to your existing PERMISSIONS object
TRANSACTION: {
  DEPOSIT: 'MAKE_DEPOSIT',
  WITHDRAWAL: 'MAKE_WITHDRAWAL',
  TRANSFER: 'INITIATE_TRANSFER',
  INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
  EXTERNAL_TRANSFER: 'EXTERNAL_TRANSFER',
  BULK_TRANSACTION: 'PROCESS_BULK_TRANSACTIONS',
  VIEW_HISTORY: 'VIEW_TRANSACTION_HISTORY',
  CANCEL: 'CANCEL_TRANSACTION',
  APPROVE: 'APPROVE_TRANSACTION',
  REJECT: 'REJECT_TRANSACTION'
},
};

export default PERMISSIONS;