// constants/transactionTypes.js
export const CORE_TX_TYPES = [
  'DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'DEBIT', 'CREDIT',
  'ADJUSTMENT', 'REVERSAL', 'CHARGE', 'REFUND', 
  'INTEREST_CREDIT', 'DIVIDEND', 'FEE'
];

export const LOAN_TX_TYPES = [
   'LOAN_DISBURSEMENT',
  'LOAN_REPAYMENT',
  'LOAN_INTEREST',
  'LOAN_FEE',
  'LOAN_PENALTY',
  'LOAN_REFINANCE',
  'LOAN_WRITEOFF',
  'LOAN_RECOVERY',
  'LOAN_RESCHEDULE',
  'ADJUSTMENT',
  'FEE',
  'LOAN_PROCESSING_FEE',
  'LOAN_LIABILITY'
];

export const INVESTMENT_TX_TYPES = [
  'INVESTMENT_BUY', 'INVESTMENT_SELL', 'INVESTMENT_DIVIDEND',
  'INVESTMENT_INTEREST', 'INVESTMENT_FEE'
];

export const CARD_TX_TYPES = [
  'CARD_PURCHASE', 'CARD_CASH_ADVANCE', 'CARD_PAYMENT',
  'CARD_FEE', 'CARD_REWARD', 'CARD_CHARGEBACK'
];

export const DIGITAL_TX_TYPES = [
  'MOBILE_PAYMENT', 'ONLINE_TRANSFER', 'BILL_PAYMENT',
  'QR_PAYMENT', 'P2P_TRANSFER'
];

export const SPECIAL_TX_TYPES = [
  'FOREIGN_EXCHANGE', 'BANK_CHARGE', 'TAX_PAYMENT',
  'ESCROW', 'SETTLEMENT', 'CORRESPONDENT',
  'NOSTRO', 'VOSTRO'
];

export const GENERAL_TX_TYPES = [
  ...CORE_TX_TYPES,
  ...DIGITAL_TX_TYPES,
  ...CARD_TX_TYPES,
  ...SPECIAL_TX_TYPES
];

export const LOAN_ACCOUNT_TX_TYPES = [
  'LOAN_DISBURSEMENT', 
  'LOAN_REPAYMENT', 
  'LOAN_INTEREST', 
  'LOAN_FEE', 
  'LOAN_PENALTY', 
  'LOAN_REFINANCE', 
  'LOAN_WRITEOFF', 
  'LOAN_RECOVERY', 
  'LOAN_RESCHEDULE', 
  'ADJUSTMENT', 
  'FEE',
  'LOAN_PROCESSING_FEE',
  'LOAN_LIABILITY'
];





export const INVESTMENT_ACCOUNT_TX_TYPES = [
  ...INVESTMENT_TX_TYPES,
  ...CORE_TX_TYPES.filter(type => 
    ['TRANSFER', 'DEBIT', 'CREDIT', 'FEE'].includes(type)
  )
];

export const getAllTransactionTypes = () => [
  ...new Set([
    ...CORE_TX_TYPES,
    ...LOAN_TX_TYPES,
    ...INVESTMENT_TX_TYPES,
    ...CARD_TX_TYPES,
    ...DIGITAL_TX_TYPES,
    ...SPECIAL_TX_TYPES
  ])
];