export const PERMISSIONS = {
  // Core Transaction Permissions
  DRAWER: {
    VIEW: 'VIEW_DRAWER',
    MANAGE: 'MANAGE_DRAWER',
    RECONCILE: 'RECONCILE_DRAWER'
  },

  // Customer Management
  CUSTOMER: {
    CREATE: 'CREATE_CUSTOMER',
    VIEW: 'VIEW_CUSTOMER',
    UPDATE: 'UPDATE_CUSTOMER',
    DELETE: 'DELETE_CUSTOMER',
    KYC_VERIFY: 'VERIFY_KYC',
    IDENTIFICATION: 'CUSTOMER_IDENTIFICATION',
    PROFILE: 'VIEW_CUSTOMER_PROFILE',
    APPROVAL: 'CUSTOMER_APPROVAL'
  },

  // Account Operations
  ACCOUNT: {
    OPEN: 'OPEN_ACCOUNT',
    CLOSE: 'CLOSE_ACCOUNT',
    FREEZE: 'FREEZE_ACCOUNT',
    VIEW_BALANCE: 'VIEW_ACCOUNT_BALANCE',
    VIEW_STATEMENT: 'VIEW_ACCOUNT_STATEMENT',
    DEPOSIT_101: 'DEPOSIT_101',
    WITHDRAWAL_102: 'WITHDRAWAL_102',
    UPDATE: 'UPDATE_ACCOUNT',
    TERM_DEPOSIT: 'CREATE_TERM_DEPOSIT'
  },

  // Loan Operations
  LOAN_OPERATIONS: {
    DISBURSE: 'DISBURSE_LOAN',
    APPROVE: 'APPROVE_LOAN',
    REJECT: 'REJECT_LOAN',
    RESTRUCTURE: 'RESTRUCTURE_LOAN',
    WRITE_OFF: 'WRITE_OFF_LOAN',
    COLLECT: 'COLLECT_LOAN',
    RECOVERY: 'RECOVER_LOAN',
    CREATE_CONTRACT: 'CREATE_LOAN_CONTRACT',
    VIEW: 'VIEW_LOAN',
    PROCESS: 'PROCESS_LOAN',
    CREDIT_APPLICATION: 'CREATE_LOAN_CREDIT_APPLICATION'
  },

  // Loan Fees
  LOAN_FEE: {
    CREATE: 'CREATE_LOAN_FEE',
    VIEW: 'VIEW_LOAN_FEES',
    UPDATE: 'UPDATE_LOAN_FEE',
    TOGGLE_STATUS: 'TOGGLE_LOAN_FEE_STATUS',
    WAIVE: 'WAIVE_LOAN_FEE',
    SETUP: 'SETUP_LOAN_FEE'
  },

  // Financial Posting
  POSTING: {
    CUSTOMER_POSTING: 'CUSTOMER_POSTING',
    GL_POSTING: 'GL_POSTING',
    REVERSE: 'REVERSE_TRANSACTION',
    ADJUST: 'ADJUST_TRANSACTION',
    CHART_OF_ACCOUNT: 'VIEW_CHART_OF_ACCOUNT',
    GL_SUBFOLDER: 'VIEW_GL_SUBFOLDER',
    VIEW_SUBFOLDER: 'VIEW_SUBFOLDER_ACCOUNT',
    DEPARTMENT: 'MANAGE_DEPARTMENT'
  },

  // Reports
  REPORT: {
    GENERATE: 'GENERATE_REPORTS',
    VIEW: 'VIEW_REPORTS',
    EXPORT: 'EXPORT_REPORTS',
    CUSTOM: 'CREATE_CUSTOM_REPORTS',
    CUSTOMER: 'VIEW_CUSTOMER_REPORT',
    TERM_DEPOSIT: 'VIEW_TERM_DEPOSIT_REPORT',
    ACCOUNT_STATEMENT: 'VIEW_ACCOUNT_STATEMENT_REPORT',
    TRIAL_BALANCE: 'VIEW_TRIAL_BALANCE_REPORT',
    INCOME_EXPENSE: 'VIEW_INCOME_EXPENSE_REPORT',
    ALL_REPORTS: 'VIEW_ALL_REPORTS',
    TELLER_SUMMARY: 'VIEW_TELLER_SUMMARY_REPORT',
    GUARANTOR: 'VIEW_GUARANTOR_REPORT',
    PERFORMANCE_METRICS: 'VIEW_PERFORMANCE_METRICS'
  },

  // ✅ **CRITICAL FIX: System Administration with User Management**
  SYSTEM_ADMIN: {
    MANAGE_USERS: 'MANAGE_USERS',
    ACTIVATE_USER: 'ACTIVATE_USER', // ✅ NEW: Specific permission for activation
    DEACTIVATE_USER: 'DEACTIVATE_USER', // ✅ NEW: Specific permission for deactivation
    CREATE_USER: 'CREATE_USER', // ✅ NEW: For creating users
    UPDATE_USER: 'UPDATE_USER', // ✅ NEW: For updating user details
    VIEW_USERS: 'VIEW_USERS', // ✅ NEW: For viewing user lists
    RESET_PASSWORD: 'RESET_PASSWORD', // ✅ NEW: For password resets
    AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
    SYSTEM_CONFIG: 'MANAGE_SYSTEM_CONFIG',
    BACKUP: 'SYSTEM_BACKUP',
    RESTORE: 'SYSTEM_RESTORE',
    SYSTEM_DATE: 'VIEW_SYSTEM_DATE',
    OS_TRIGGER: 'TRIGGER_OS_OPERATIONS',
    LICENSE_DETAILS: 'VIEW_LICENSE_DETAILS'
  },

  // Permission Management
  PERMISSION_MANAGEMENT: {
    CREATE_PERMISSION: 'CREATE_PERMISSION',
    VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
    UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',
    ASSIGN_ROLES: 'ASSIGN_ROLES',
    CLONE_ROLES: 'CLONE_ROLE_PERMISSIONS',
    BUSINESS_ROLE: 'MANAGE_BUSINESS_ROLE',
    BUSINESS_ROLE_LIST: 'VIEW_BUSINESS_ROLE_LIST',
    BU_ROLE_CREATION: 'CREATE_BUSINESS_ROLE',
    BUSINESS_ROLE_QUEUE: 'VIEW_BUSINESS_ROLE_QUEUE',
    BUSINESS_ROLE_QUEUE_SETUP: 'SETUP_BUSINESS_ROLE_QUEUE'
  },

  // Dashboard Access
  DASHBOARD: {
    VIEW: 'VIEW_DASHBOARD',
    CUSTOMIZE: 'CUSTOMIZE_DASHBOARD',
    SHARE: 'SHARE_DASHBOARD',
    TELLER_DASHBOARD: 'VIEW_TELLER_DASHBOARD',
    TRANSACTION_OVERVIEW: 'VIEW_TRANSACTION_OVERVIEW',
    QUICK_ACTIONS: 'ACCESS_QUICK_ACTIONS',
    REAL_TIME_STATS: 'VIEW_REAL_TIME_STATS',
    CREDIT_OFFICER_DASHBOARD: 'VIEW_CREDIT_OFFICER_DASHBOARD',
    MANAGER_DASHBOARD: 'VIEW_MANAGER_DASHBOARD',
    GUARANTOR_DASHBOARD: 'VIEW_GUARANTOR_DASHBOARD',
    BU_PERFORMANCE: 'VIEW_BU_PERFORMANCE',
    DASHBOARDSTATS: 'DASHBOARD_REAL_TIME_STATS'
  },

  // Credit Application
  CREDIT_APPL: {
    CREATE: 'CREATE_CREDIT_APP',
    REVIEW: 'REVIEW_CREDIT_APP',
    APPROVE: 'APPROVE_CREDIT_APP',
    REJECT: 'REJECT_CREDIT_APP'
  },

  // Fixed Assets
  FIXED_ASSET: {
    VIEW: 'VIEW_FIXED_ASSET',
    REGISTER: 'REGISTER_ASSET',
    DEPRECIATE: 'CALC_DEPRECIATION',
    DISPOSE: 'DISPOSE_ASSET',
    TRANSFER: 'TRANSFER_ASSET'
  },

  // Approvals
  APPROVAL: {
    FINANCIAL: 'APPROVE_FINANCIAL',
    TRANSACTION: 'APPROVE_TRANSACTION',
    CUSTOMER_RELATED: 'APPROVE_CUSTOMER_ACTION',
    LOAN: 'APPROVE_LOAN',
    MANAGER: 'MANAGER_APPROVAL',
    CASH_DEPOSIT: 'APPROVE_CASH_DEPOSIT',
    GL_TRANSACTION: 'APPROVE_GL_TRANSACTION',
    GUARANTOR: 'APPROVE_GUARANTOR',
    DEPOSIT_APPLICATION: 'DEPOSIT_APPLICATION_APPROVAL',
    STANDING_ORDER: 'APPROVE_STANDING_ORDER',
    USER_ACTIVATION: 'APPROVE_USER_ACTIVATION' // ✅ NEW: For user activation/deactivation approvals
  },

  // Treasury
  TREASURY: {
    VIEW: 'TREASURY_VIEW',
    MANAGE: 'TREASURY_MANAGE',
    APPROVE: 'TREASURY_APPROVE'
  },

  // Operations
  OPERATIONS: {
    VIEW: 'OPERATIONS_VIEW',
    MANAGE: 'OPERATIONS_MANAGE',
    APPROVE: 'OPERATIONS_APPROVE'
  },

  // Transactions
  TRANSACTION: {
    DEPOSIT: 'MAKE_DEPOSIT',
    WITHDRAWAL: 'MAKE_WITHDRAWAL',
    TRANSFER: 'INITIATE_TRANSFER',
    INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
    EXTERNAL_TRANSFER: 'EXTERNAL_TRANSFER',
    BULK_TRANSACTION: 'PROCESS_BULK_TRANSACTIONS',
    VIEW_HISTORY: 'VIEW_TRANSACTION_HISTORY',
    CANCEL: 'CANCEL_TRANSACTION',
    APPROVE: 'APPROVE_TRANSACTION',
    REJECT: 'REJECT_TRANSACTION',
    OPENING_DEPOSIT: 'MAKE_OPENING_DEPOSIT',
    GL_TO_GL: 'PROCESS_GL_TO_GL',
    CREDIT_GL: 'PROCESS_CREDIT_GL',
    DEBIT_GL: 'PROCESS_DEBIT_GL',
    REPRINT_RECEIPT: 'REPRINT_TRANSACTION_RECEIPT',
    VIEW_RECENT: 'VIEW_RECENT_TRANSACTIONS',
    VIEW_STATS: 'VIEW_TRANSACTION_STATS'
  },

  // Workflow Management
  WORKFLOW: {
    CONFIGURE: 'CONFIGURE_WORKFLOW',
    MANAGE_SUBPROCESS: 'MANAGE_WORKFLOW_SUBPROCESS'
  },

  // AML (Anti-Money Laundering)
  AML: {
    VIEW_THRESHOLD: 'VIEW_AML_THRESHOLD',
    APPROVE: 'APPROVE_AML',
    CONFIGURE: 'CONFIGURE_AML',
    MONITOR: 'MONITOR_AML',
    REPORT: 'GENERATE_AML_REPORT',
    SUSPEND: 'SUSPEND_AML_TRANSACTION'
  },

  // Business Unit
  BUSINESS_UNIT: {
    CREATE: 'CREATE_BUSINESS_UNIT',
    VIEW: 'VIEW_BUSINESS_UNIT',
    SECURITY: 'MANAGE_SECURITY_BUSINESS_UNIT',
    ROLE: 'MANAGE_BUSINESS_UNIT_ROLE'
  },

  // Security Profile
  SECURITY_PROFILE: {
    ADD_USER: 'ADD_USER',
    ASSIGN_ROLE: 'ASSIGN_USER_ROLE',
    ASSIGN_CSO_RIGHT: 'ASSIGN_CSO_RIGHT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    CONSOLE: 'VIEW_SECURITY_CONSOLE'
  },

  // Deposit Management
  DEPOSIT: {
    CREATE: 'CREATE_DEPOSIT',
    APPLICATION: 'CREATE_DEPOSIT_APPLICATION',
    VIEW_DETAILS: 'VIEW_DEPOSIT_DETAILS',
    APPROVAL: 'DEPOSIT_APPLICATION_APPROVAL'
  },

  // Guarantor Management
  GUARANTOR: {
    CREATE: 'CREATE_GUARANTOR',
    VIEW: 'VIEW_GUARANTOR',
    VIEW_DETAILS: 'VIEW_GUARANTOR_DETAILS',
    UPDATE: 'UPDATE_GUARANTOR',
    DELETE: 'DELETE_GUARANTOR',
    SEARCH: 'SEARCH_GUARANTOR',
    APPROVE: 'APPROVE_GUARANTOR',
    REJECT: 'REJECT_GUARANTOR',
    VERIFY: 'VERIFY_GUARANTOR',
    REMOVAL_REQUEST: 'REQUEST_GUARANTOR_REMOVAL',
    APPROVE_REMOVAL: 'APPROVE_GUARANTOR_REMOVAL',
    REJECT_REMOVAL: 'REJECT_GUARANTOR_REMOVAL',
    REACTIVATE: 'REACTIVATE_GUARANTOR',
    DEACTIVATE: 'DEACTIVATE_GUARANTOR',
    BULK_ACTIONS: 'PERFORM_GUARANTOR_BULK_ACTIONS',
    REPORTS: 'VIEW_GUARANTOR_REPORTS',
    DASHBOARD: 'VIEW_GUARANTOR_DASHBOARD',
    AUDIT_LOG: 'VIEW_GUARANTOR_AUDIT_LOG',
    EXPORT: 'EXPORT_GUARANTOR_DATA'
  },

  // Rate Management
  RATE: {
    LOAN_INTEREST: 'SETUP_LOAN_INTEREST',
    DEPOSIT_INTEREST: 'SETUP_DEPOSIT_INTEREST',
    INDEX: 'SETUP_INDEX_RATE'
  },

  // Product Management
  PRODUCT: {
    VIEW: 'VIEW_PRODUCT',
    SETUP: 'SETUP_PRODUCT',
    LOAN: 'SETUP_LOAN_PRODUCT',
    MAPPING: 'MANAGE_PRODUCT_MAPPING'
  },

  // Holiday Management
  HOLIDAY: {
    MANAGE: 'MANAGE_HOLIDAY_CALENDAR'
  },

  // Marketing
  MARKETING: {
    CREATE_CAMPAIGN: 'CREATE_MARKETING_CAMPAIGN',
    VIEW_ANALYTICS: 'VIEW_MARKETING_ANALYTICS'
  },

  // Agency Banking
  AGENCY: {
    MANAGE_AGENCY: 'MANAGE_AGENCY_BANKING',
    VIEW_AGENCY_REPORT: 'VIEW_AGENCY_REPORT'
  },

  // Analytics
  ANALYTICS: {
    VIEW_BUSINESS_ANALYTICS: 'VIEW_BUSINESS_ANALYTICS',
    EXPORT_ANALYTICS: 'EXPORT_ANALYTICS_DATA',
    VIEW_TELLER_ANALYTICS: 'VIEW_TELLER_ANALYTICS'
  },

  // Risk Management
  RISK: {
    VIEW_RISK_REPORT: 'VIEW_RISK_REPORT',
    MANAGE_RISK_SETTINGS: 'MANAGE_RISK_SETTINGS'
  },

  // Reconciliation
  RECONCILIATION: {
    PROCESS_RECONCILIATION: 'PROCESS_RECONCILIATION',
    VIEW_RECONCILIATION_REPORT: 'VIEW_RECONCILIATION_REPORT'
  },

  // Thrift Management
  THRIFT: {
    CREATE: 'CREATE_THRIFT',
    COLLECTION: 'COLLECT_THRIFT',
    WITHDRAWAL: 'WITHDRAWAL_THRIFT'
  },

  // Standing Order Management
  STANDING_ORDER: {
    CREATE: 'CREATE_STANDING_ORDER',
    VIEW: 'VIEW_STANDING_ORDER',
    UPDATE: 'UPDATE_STANDING_ORDER',
    DELETE: 'DELETE_STANDING_ORDER'
  },

  // Performance & Monitoring Permissions
  PERFORMANCE: {
    VIEW_METRICS: 'VIEW_PERFORMANCE_METRICS',
    VIEW_TELLER_PERFORMANCE: 'VIEW_TELLER_PERFORMANCE',
    VIEW_BRANCH_PERFORMANCE: 'VIEW_BRANCH_PERFORMANCE',
    EXPORT_PERFORMANCE_DATA: 'EXPORT_PERFORMANCE_DATA'
  },

  // Dashboard Statistics Permissions
  STATISTICS: {
    VIEW_REAL_TIME: 'VIEW_REAL_TIME_STATISTICS',
    VIEW_HISTORICAL: 'VIEW_HISTORICAL_STATISTICS',
    VIEW_FINANCIAL: 'VIEW_FINANCIAL_STATISTICS',
    VIEW_OPERATIONAL: 'VIEW_OPERATIONAL_STATISTICS'
  },

  // ✅ **NEW: User Management Module Permissions**
  USER_MANAGEMENT: {
    MODULE: 'MANAGE_USERS_MODULE', // ✅ Main module permission
    ACTIVATE: 'ACTIVATE_USER',
    DEACTIVATE: 'DEACTIVATE_USER',
    CREATE: 'CREATE_USER',
    UPDATE: 'UPDATE_USER',
    VIEW: 'VIEW_USERS',
    DELETE: 'DELETE_USER',
    RESET_PASSWORD: 'RESET_USER_PASSWORD',
    ASSIGN_ROLES: 'ASSIGN_USER_ROLES',
    VIEW_PROFILE: 'VIEW_USER_PROFILE',
    EXPORT: 'EXPORT_USER_DATA'
  }
};

export default PERMISSIONS;