export const PERMISSIONS = {
  // Core Transaction Permissions
  DRAWER: {
    VIEW: 'VIEW_DRAWER',
    MANAGE: 'MANAGE_DRAWER',
    RECONCILE: 'RECONCILE_DRAWER'
  },

  // Customer Management
  CUSTOMER: {
    CREATE: 'CREATE_CUSTOMER',
    VIEW: 'VIEW_CUSTOMER',
    UPDATE: 'UPDATE_CUSTOMER',
    DELETE: 'DELETE_CUSTOMER',
    KYC_VERIFY: 'VERIFY_KYC',
    IDENTIFICATION: 'CUSTOMER_IDENTIFICATION',
    PROFILE: 'VIEW_CUSTOMER_PROFILE',
    APPROVAL: 'CUSTOMER_APPROVAL'
  },

  // Account Operations
  ACCOUNT: {
    OPEN: 'OPEN_ACCOUNT',
    CLOSE: 'CLOSE_ACCOUNT',
    FREEZE: 'FREEZE_ACCOUNT',
    VIEW_BALANCE: 'VIEW_ACCOUNT_BALANCE',
    VIEW_STATEMENT: 'VIEW_ACCOUNT_STATEMENT',
    DEPOSIT_101: 'DEPOSIT_101',
    WITHDRAWAL_102: 'WITHDRAWAL_102',
    UPDATE: 'UPDATE_ACCOUNT',
    TERM_DEPOSIT: 'CREATE_TERM_DEPOSIT'
  },

  // ✅ ADDED: Manual Loan Repayment Permissions (for your controller)
  LOAN_REPAYMENT: {
    MANUAL: 'MANUAL_LOAN_REPAYMENT',
    PROCESS: 'PROCESS_LOAN_REPAYMENT',
    VIEW_SCHEDULE: 'VIEW_LOAN_REPAYMENT_SCHEDULE',
    OVERRIDE: 'OVERRIDE_LOAN_REPAYMENT',
    PARTIAL: 'PROCESS_PARTIAL_REPAYMENT',
    ADVANCE: 'PROCESS_ADVANCE_REPAYMENT',
    RESCHEDULE: 'RESCHEDULE_REPAYMENT',
    REVERSE: 'REVERSE_LOAN_REPAYMENT',
    VIEW_HISTORY: 'VIEW_REPAYMENT_HISTORY',
    PRINT_RECEIPT: 'PRINT_REPAYMENT_RECEIPT',
    EXPORT: 'EXPORT_REPAYMENT_DATA'
  },

  // ✅ ADDED: Group Loan Permissions (for your bulk repayment controller)
  GROUP_LOAN: {
    CREATE: 'CREATE_GROUP_LOAN',
    VIEW: 'VIEW_GROUP_LOAN',
    UPDATE: 'UPDATE_GROUP_LOAN',
    DISBURSE: 'DISBURSE_GROUP_LOAN',
    APPROVE: 'APPROVE_GROUP_LOAN',
    REJECT: 'REJECT_GROUP_LOAN',
    MANAGE_MEMBERS: 'MANAGE_GROUP_LOAN_MEMBERS',
    PROCESS_REPAYMENT: 'PROCESS_GROUP_LOAN_REPAYMENT',
    VIEW_SCHEDULE: 'VIEW_GROUP_LOAN_SCHEDULE',
    BULK_REPAYMENT: 'PROCESS_BULK_GROUP_LOAN_REPAYMENT',
    COLLECT_SAVINGS: 'COLLECT_GROUP_SAVINGS',
    VIEW_REPORTS: 'VIEW_GROUP_LOAN_REPORTS',
    EXPORT_DATA: 'EXPORT_GROUP_LOAN_DATA',
    AUDIT: 'VIEW_GROUP_LOAN_AUDIT'
  },

  // Loan Operations
  LOAN_OPERATIONS: {
    DISBURSE: 'DISBURSE_LOAN',
    APPROVE: 'APPROVE_LOAN',
    REJECT: 'REJECT_LOAN',
    RESTRUCTURE: 'RESTRUCTURE_LOAN',
    WRITE_OFF: 'WRITE_OFF_LOAN',
    COLLECT: 'COLLECT_LOAN',
    RECOVERY: 'RECOVER_LOAN',
    CREATE_CONTRACT: 'CREATE_LOAN_CONTRACT',
    VIEW: 'VIEW_LOAN',
    PROCESS: 'PROCESS_LOAN',
    CREDIT_APPLICATION: 'CREATE_LOAN_CREDIT_APPLICATION',
    // ✅ ADDED for your controller
    MANUAL_REPAYMENT: 'PROCESS_MANUAL_LOAN_REPAYMENT',
    BULK_REPAYMENT: 'PROCESS_BULK_LOAN_REPAYMENTS'
  },

  // Loan Fees
  LOAN_FEE: {
    CREATE: 'CREATE_LOAN_FEE',
    VIEW: 'VIEW_LOAN_FEES',
    UPDATE: 'UPDATE_LOAN_FEE',
    TOGGLE_STATUS: 'TOGGLE_LOAN_FEE_STATUS',
    WAIVE: 'WAIVE_LOAN_FEE',
    SETUP: 'SETUP_LOAN_FEE'
  },

  // Financial Posting
  POSTING: {
    CUSTOMER_POSTING: 'CUSTOMER_POSTING',
    GL_POSTING: 'GL_POSTING',
    REVERSE: 'REVERSE_TRANSACTION',
    ADJUST: 'ADJUST_TRANSACTION',
    CHART_OF_ACCOUNT: 'VIEW_CHART_OF_ACCOUNT',
    GL_SUBFOLDER: 'VIEW_GL_SUBFOLDER',
    VIEW_SUBFOLDER: 'VIEW_SUBFOLDER_ACCOUNT',
    DEPARTMENT: 'MANAGE_DEPARTMENT'
  },

  // Reports
  REPORT: {
    GENERATE: 'GENERATE_REPORTS',
    VIEW: 'VIEW_REPORTS',
    EXPORT: 'EXPORT_REPORTS',
    CUSTOM: 'CREATE_CUSTOM_REPORTS',
    CUSTOMER: 'VIEW_CUSTOMER_REPORT',
    TERM_DEPOSIT: 'VIEW_TERM_DEPOSIT_REPORT',
    ACCOUNT_STATEMENT: 'VIEW_ACCOUNT_STATEMENT_REPORT',
    TRIAL_BALANCE: 'VIEW_TRIAL_BALANCE_REPORT',
    INCOME_EXPENSE: 'VIEW_INCOME_EXPENSE_REPORT',
    ALL_REPORTS: 'VIEW_ALL_REPORTS',
    TELLER_SUMMARY: 'VIEW_TELLER_SUMMARY_REPORT',
    GUARANTOR: 'VIEW_GUARANTOR_REPORT',
    PERFORMANCE_METRICS: 'VIEW_PERFORMANCE_METRICS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'VIEW_LOAN_REPAYMENT_REPORT',
    GROUP_LOAN: 'VIEW_GROUP_LOAN_REPORT',
    BULK_REPAYMENT: 'VIEW_BULK_REPAYMENT_REPORT'
  },

  // System Administration with User Management
  SYSTEM_ADMIN: {
    MANAGE_USERS: 'MANAGE_USERS',
    ACTIVATE_USER: 'ACTIVATE_USER',
    DEACTIVATE_USER: 'DEACTIVATE_USER',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    VIEW_USERS: 'VIEW_USERS',
    RESET_PASSWORD: 'RESET_PASSWORD',
    AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
    SYSTEM_CONFIG: 'MANAGE_SYSTEM_CONFIG',
    BACKUP: 'SYSTEM_BACKUP',
    RESTORE: 'SYSTEM_RESTORE',
    SYSTEM_DATE: 'VIEW_SYSTEM_DATE',
    OS_TRIGGER: 'TRIGGER_OS_OPERATIONS',
    LICENSE_DETAILS: 'VIEW_LICENSE_DETAILS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_CONFIG: 'CONFIGURE_LOAN_REPAYMENT'
  },

  // Permission Management
  PERMISSION_MANAGEMENT: {
    CREATE_PERMISSION: 'CREATE_PERMISSION',
    VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
    UPDATE_PERMISSIONS: 'UPDATE_PERMISSIONS',
    ASSIGN_ROLES: 'ASSIGN_ROLES',
    CLONE_ROLES: 'CLONE_ROLE_PERMISSIONS',
    BUSINESS_ROLE: 'MANAGE_BUSINESS_ROLE',
    BUSINESS_ROLE_LIST: 'VIEW_BUSINESS_ROLE_LIST',
    BU_ROLE_CREATION: 'CREATE_BUSINESS_ROLE',
    BUSINESS_ROLE_QUEUE: 'VIEW_BUSINESS_ROLE_QUEUE',
    BUSINESS_ROLE_QUEUE_SETUP: 'SETUP_BUSINESS_ROLE_QUEUE'
  },

  // Dashboard Access
  DASHBOARD: {
    VIEW: 'VIEW_DASHBOARD',
    CUSTOMIZE: 'CUSTOMIZE_DASHBOARD',
    SHARE: 'SHARE_DASHBOARD',
    TELLER_DASHBOARD: 'VIEW_TELLER_DASHBOARD',
    TRANSACTION_OVERVIEW: 'VIEW_TRANSACTION_OVERVIEW',
    QUICK_ACTIONS: 'ACCESS_QUICK_ACTIONS',
    REAL_TIME_STATS: 'VIEW_REAL_TIME_STATS',
    CREDIT_OFFICER_DASHBOARD: 'VIEW_CREDIT_OFFICER_DASHBOARD',
    MANAGER_DASHBOARD: 'VIEW_MANAGER_DASHBOARD',
    GUARANTOR_DASHBOARD: 'VIEW_GUARANTOR_DASHBOARD',
    BU_PERFORMANCE: 'VIEW_BU_PERFORMANCE',
    DASHBOARDSTATS: 'DASHBOARD_REAL_TIME_STATS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_STATS: 'VIEW_LOAN_REPAYMENT_STATS',
    GROUP_LOAN_STATS: 'VIEW_GROUP_LOAN_STATS'
  },

  // Credit Application
  CREDIT_APPL: {
    CREATE: 'CREATE_CREDIT_APP',
    REVIEW: 'REVIEW_CREDIT_APP',
    APPROVE: 'APPROVE_CREDIT_APP',
    REJECT: 'REJECT_CREDIT_APP'
  },

  // Fixed Assets
  FIXED_ASSET: {
    VIEW: 'VIEW_FIXED_ASSET',
    REGISTER: 'REGISTER_ASSET',
    DEPRECIATE: 'CALC_DEPRECIATION',
    DISPOSE: 'DISPOSE_ASSET',
    TRANSFER: 'TRANSFER_ASSET'
  },

  // Approvals
  APPROVAL: {
    FINANCIAL: 'APPROVE_FINANCIAL',
    TRANSACTION: 'APPROVE_TRANSACTION',
    CUSTOMER_RELATED: 'APPROVE_CUSTOMER_ACTION',
    LOAN: 'APPROVE_LOAN',
    MANAGER: 'MANAGER_APPROVAL',
    CASH_DEPOSIT: 'APPROVE_CASH_DEPOSIT',
    GL_TRANSACTION: 'APPROVE_GL_TRANSACTION',
    GUARANTOR: 'APPROVE_GUARANTOR',
    DEPOSIT_APPLICATION: 'DEPOSIT_APPLICATION_APPROVAL',
    STANDING_ORDER: 'APPROVE_STANDING_ORDER',
    USER_ACTIVATION: 'APPROVE_USER_ACTIVATION',
    VAULT_ACCESS: 'APPROVE_VAULT_ACCESS',
    VAULT_OPERATION: 'APPROVE_VAULT_OPERATION',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'APPROVE_LOAN_REPAYMENT',
    GROUP_LOAN: 'APPROVE_GROUP_LOAN',
    BULK_REPAYMENT: 'APPROVE_BULK_REPAYMENT'
  },

  // Treasury
  TREASURY: {
    VIEW: 'TREASURY_VIEW',
    MANAGE: 'TREASURY_MANAGE',
    APPROVE: 'TREASURY_APPROVE'
  },

  // Operations
  OPERATIONS: {
    VIEW: 'OPERATIONS_VIEW',
    MANAGE: 'OPERATIONS_MANAGE',
    APPROVE: 'OPERATIONS_APPROVE',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'OPERATIONS_LOAN_REPAYMENT'
  },

  // Transactions
  TRANSACTION: {
    DEPOSIT: 'MAKE_DEPOSIT',
    WITHDRAWAL: 'MAKE_WITHDRAWAL',
    TRANSFER: 'INITIATE_TRANSFER',
    INTERNAL_TRANSFER: 'INTERNAL_TRANSFER',
    EXTERNAL_TRANSFER: 'EXTERNAL_TRANSFER',
    BULK_TRANSACTION: 'PROCESS_BULK_TRANSACTIONS',
    VIEW_HISTORY: 'VIEW_TRANSACTION_HISTORY',
    CANCEL: 'CANCEL_TRANSACTION',
    APPROVE: 'APPROVE_TRANSACTION',
    REJECT: 'REJECT_TRANSACTION',
    OPENING_DEPOSIT: 'MAKE_OPENING_DEPOSIT',
    GL_TO_GL: 'PROCESS_GL_TO_GL',
    CREDIT_GL: 'PROCESS_CREDIT_GL',
    DEBIT_GL: 'PROCESS_DEBIT_GL',
    REPRINT_RECEIPT: 'REPRINT_TRANSACTION_RECEIPT',
    VIEW_RECENT: 'VIEW_RECENT_TRANSACTIONS',
    VIEW_STATS: 'VIEW_TRANSACTION_STATS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'PROCESS_LOAN_REPAYMENT_TRANSACTION'
  },

  // Workflow Management
  WORKFLOW: {
    CONFIGURE: 'CONFIGURE_WORKFLOW',
    MANAGE_SUBPROCESS: 'MANAGE_WORKFLOW_SUBPROCESS',
    // ✅ ADDED missing VIEW permission
    VIEW: 'WORKFLOW.VIEW',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'MANAGE_LOAN_REPAYMENT_WORKFLOW',
    GROUP_LOAN: 'MANAGE_GROUP_LOAN_WORKFLOW'
  },

  // AML (Anti-Money Laundering)
  AML: {
    VIEW_THRESHOLD: 'VIEW_AML_THRESHOLD',
    APPROVE: 'APPROVE_AML',
    CONFIGURE: 'CONFIGURE_AML',
    MONITOR: 'MONITOR_AML',
    REPORT: 'GENERATE_AML_REPORT',
    SUSPEND: 'SUSPEND_AML_TRANSACTION',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT: 'MONITOR_LOAN_REPAYMENT_AML'
  },

  // Business Unit
  BUSINESS_UNIT: {
    CREATE: 'CREATE_BUSINESS_UNIT',
    VIEW: 'VIEW_BUSINESS_UNIT',
    SECURITY: 'MANAGE_SECURITY_BUSINESS_UNIT',
    ROLE: 'MANAGE_BUSINESS_UNIT_ROLE'
  },

  // Security Profile
  SECURITY_PROFILE: {
    ADD_USER: 'ADD_USER',
    ASSIGN_ROLE: 'ASSIGN_USER_ROLE',
    ASSIGN_CSO_RIGHT: 'ASSIGN_CSO_RIGHT',
    RESET_PASSWORD: 'RESET_PASSWORD',
    CONSOLE: 'VIEW_SECURITY_CONSOLE'
  },

  // Deposit Management
  DEPOSIT: {
    CREATE: 'CREATE_DEPOSIT',
    APPLICATION: 'CREATE_DEPOSIT_APPLICATION',
    VIEW_DETAILS: 'VIEW_DEPOSIT_DETAILS',
    APPROVAL: 'DEPOSIT_APPLICATION_APPROVAL'
  },

  // Guarantor Management
  GUARANTOR: {
    CREATE: 'CREATE_GUARANTOR',
    VIEW: 'VIEW_GUARANTOR',
    VIEW_DETAILS: 'VIEW_GUARANTOR_DETAILS',
    UPDATE: 'UPDATE_GUARANTOR',
    DELETE: 'DELETE_GUARANTOR',
    SEARCH: 'SEARCH_GUARANTOR',
    APPROVE: 'APPROVE_GUARANTOR',
    REJECT: 'REJECT_GUARANTOR',
    VERIFY: 'VERIFY_GUARANTOR',
    REMOVAL_REQUEST: 'REQUEST_GUARANTOR_REMOVAL',
    APPROVE_REMOVAL: 'APPROVE_GUARANTOR_REMOVAL',
    REJECT_REMOVAL: 'REJECT_GUARANTOR_REMOVAL',
    REACTIVATE: 'REACTIVATE_GUARANTOR',
    DEACTIVATE: 'DEACTIVATE_GUARANTOR',
    BULK_ACTIONS: 'PERFORM_GUARANTOR_BULK_ACTIONS',
    REPORTS: 'VIEW_GUARANTOR_REPORTS',
    DASHBOARD: 'VIEW_GUARANTOR_DASHBOARD',
    AUDIT_LOG: 'VIEW_GUARANTOR_AUDIT_LOG',
    EXPORT: 'EXPORT_GUARANTOR_DATA'
  },

  // Rate Management
  RATE: {
    LOAN_INTEREST: 'SETUP_LOAN_INTEREST',
    DEPOSIT_INTEREST: 'SETUP_DEPOSIT_INTEREST',
    INDEX: 'SETUP_INDEX_RATE',
    // ✅ ADDED for your controller
    PENALTY: 'SETUP_LOAN_PENALTY_RATE'
  },

  // Product Management
  PRODUCT: {
    VIEW: 'VIEW_PRODUCT',
    SETUP: 'SETUP_PRODUCT',
    LOAN: 'SETUP_LOAN_PRODUCT',
    MAPPING: 'MANAGE_PRODUCT_MAPPING'
  },

  // Holiday Management
  HOLIDAY: {
    MANAGE: 'MANAGE_HOLIDAY_CALENDAR'
  },

  // Marketing
  MARKETING: {
    CREATE_CAMPAIGN: 'CREATE_MARKETING_CAMPAIGN',
    VIEW_ANALYTICS: 'VIEW_MARKETING_ANALYTICS'
  },

  // Agency Banking
  AGENCY: {
    MANAGE_AGENCY: 'MANAGE_AGENCY_BANKING',
    VIEW_AGENCY_REPORT: 'VIEW_AGENCY_REPORT'
  },

  // Analytics
  ANALYTICS: {
    VIEW_BUSINESS_ANALYTICS: 'VIEW_BUSINESS_ANALYTICS',
    EXPORT_ANALYTICS: 'EXPORT_ANALYTICS_DATA',
    VIEW_TELLER_ANALYTICS: 'VIEW_TELLER_ANALYTICS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_ANALYTICS: 'VIEW_LOAN_REPAYMENT_ANALYTICS'
  },

  // Risk Management
  RISK: {
    VIEW_RISK_REPORT: 'VIEW_RISK_REPORT',
    MANAGE_RISK_SETTINGS: 'MANAGE_RISK_SETTINGS',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_RISK: 'ASSESS_LOAN_REPAYMENT_RISK'
  },

  // Reconciliation
  RECONCILIATION: {
    PROCESS_RECONCILIATION: 'PROCESS_RECONCILIATION',
    VIEW_RECONCILIATION_REPORT: 'VIEW_RECONCILIATION_REPORT',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_RECONCILE: 'RECONCILE_LOAN_REPAYMENTS'
  },

  // Thrift Management
  THRIFT: {
    CREATE: 'CREATE_THRIFT',
    COLLECTION: 'COLLECT_THRIFT',
    WITHDRAWAL: 'WITHDRAWAL_THRIFT'
  },

  // Standing Order Management
  STANDING_ORDER: {
    CREATE: 'CREATE_STANDING_ORDER',
    VIEW: 'VIEW_STANDING_ORDER',
    UPDATE: 'UPDATE_STANDING_ORDER',
    DELETE: 'DELETE_STANDING_ORDER'
  },

  // Performance & Monitoring Permissions
  PERFORMANCE: {
    VIEW_METRICS: 'VIEW_PERFORMANCE_METRICS',
    VIEW_TELLER_PERFORMANCE: 'VIEW_TELLER_PERFORMANCE',
    VIEW_BRANCH_PERFORMANCE: 'VIEW_BRANCH_PERFORMANCE',
    EXPORT_PERFORMANCE_DATA: 'EXPORT_PERFORMANCE_DATA',
    // ✅ ADDED for your controller
    LOAN_REPAYMENT_PERFORMANCE: 'VIEW_LOAN_REPAYMENT_PERFORMANCE'
  },

  // Dashboard Statistics Permissions
  STATISTICS: {
    VIEW_REAL_TIME: 'VIEW_REAL_TIME_STATISTICS',
    VIEW_HISTORICAL: 'VIEW_HISTORICAL_STATISTICS',
    VIEW_FINANCIAL: 'VIEW_FINANCIAL_STATISTICS',
    VIEW_OPERATIONAL: 'VIEW_OPERATIONAL_STATISTICS'
  },

  // User Management Module Permissions
  USER_MANAGEMENT: {
    MODULE: 'MANAGE_USERS_MODULE',
    ACTIVATE: 'ACTIVATE_USER',
    DEACTIVATE: 'DEACTIVATE_USER',
    CREATE: 'CREATE_USER',
    UPDATE: 'UPDATE_USER',
    VIEW: 'VIEW_USERS',
    DELETE: 'DELETE_USER',
    RESET_PASSWORD: 'RESET_USER_PASSWORD',
    ASSIGN_ROLES: 'ASSIGN_USER_ROLES',
    VIEW_PROFILE: 'VIEW_USER_PROFILE',
    EXPORT: 'EXPORT_USER_DATA'
  },

  // Group Management
  GROUP: {
    CREATE: 'GROUP.CREATE',
    SAVINGS_MANAGEMENT: 'GROUP.SAVINGS_MANAGEMENT',
    VIEW: 'VIEW_GROUP',
    UPDATE: 'UPDATE_GROUP',
    DELETE: 'DELETE_GROUP',
    MEMBER_MANAGEMENT: 'MANAGE_GROUP_MEMBERS',
    APPROVE: 'APPROVE_GROUP',
    REPORTS: 'VIEW_GROUP_REPORTS',
    DASHBOARD: 'VIEW_GROUP_DASHBOARD',
    BULK_ACTIONS: 'PERFORM_GROUP_BULK_ACTIONS'
  },

  // ✅ ADDED: Audit Trail Permissions (for your controller)
  AUDIT: {
    VIEW_LOGS: 'VIEW_AUDIT_LOGS',
    VIEW_TRANSACTION_AUDIT: 'VIEW_TRANSACTION_AUDIT',
    VIEW_USER_AUDIT: 'VIEW_USER_AUDIT',
    VIEW_SYSTEM_AUDIT: 'VIEW_SYSTEM_AUDIT',
    EXPORT_AUDIT: 'EXPORT_AUDIT_LOGS',
    VIEW_LOAN_REPAYMENT_AUDIT: 'VIEW_LOAN_REPAYMENT_AUDIT',
    VIEW_GROUP_LOAN_AUDIT: 'VIEW_GROUP_LOAN_AUDIT',
    VIEW_BULK_REPAYMENT_AUDIT: 'VIEW_BULK_REPAYMENT_AUDIT'
  },

  // ✅ ADDED: Notification Permissions (for your controller)
  NOTIFICATION: {
    VIEW: 'VIEW_NOTIFICATIONS',
    MANAGE: 'MANAGE_NOTIFICATIONS',
    SEND: 'SEND_NOTIFICATIONS',
    CONFIGURE: 'CONFIGURE_NOTIFICATION_SETTINGS',
    LOAN_REPAYMENT_NOTIFY: 'SEND_LOAN_REPAYMENT_NOTIFICATIONS'
  },

  // ✅ ADDED: Bulk Operations Permissions (for your controller)
  BULK_OPERATIONS: {
    PROCESS: 'PROCESS_BULK_OPERATIONS',
    UPLOAD: 'UPLOAD_BULK_DATA',
    DOWNLOAD: 'DOWNLOAD_BULK_TEMPLATES',
    VALIDATE: 'VALIDATE_BULK_DATA',
    EXECUTE: 'EXECUTE_BULK_OPERATIONS',
    BULK_LOAN_REPAYMENT: 'PROCESS_BULK_LOAN_REPAYMENTS',
    BULK_GROUP_REPAYMENT: 'PROCESS_BULK_GROUP_REPAYMENTS',
    BULK_CSV_IMPORT: 'IMPORT_BULK_CSV_DATA',
    BULK_CSV_EXPORT: 'EXPORT_BULK_CSV_DATA'
  },

  // ✅ ADDED: Print & Export Permissions (for your controller)
  PRINT_EXPORT: {
    PRINT_RECEIPT: 'PRINT_RECEIPT',
    PRINT_REPORT: 'PRINT_REPORT',
    EXPORT_CSV: 'EXPORT_CSV',
    EXPORT_PDF: 'EXPORT_PDF',
    EXPORT_EXCEL: 'EXPORT_EXCEL',
    PRINT_LOAN_REPAYMENT_RECEIPT: 'PRINT_LOAN_REPAYMENT_RECEIPT',
    PRINT_BULK_REPAYMENT_RECEIPT: 'PRINT_BULK_REPAYMENT_RECEIPT',
    EXPORT_BULK_REPAYMENT: 'EXPORT_BULK_REPAYMENT_DATA'
  },

  // ✅ ADDED: Queue Management Permissions (for your controller)
  QUEUE: {
    VIEW_QUEUE: 'VIEW_QUEUE',
    MANAGE_QUEUE: 'MANAGE_QUEUE',
    PROCESS_QUEUE: 'PROCESS_QUEUE_ITEMS',
    REORDER_QUEUE: 'REORDER_QUEUE',
    CLEAR_QUEUE: 'CLEAR_QUEUE',
    LOAN_REPAYMENT_QUEUE: 'MANAGE_LOAN_REPAYMENT_QUEUE',
    BULK_REPAYMENT_QUEUE: 'MANAGE_BULK_REPAYMENT_QUEUE'
  },

  // ✅ ADDED: Help & Support Permissions
  HELP: {
    VIEW_HELP: 'VIEW_HELP_DOCUMENTATION',
    CREATE_TICKET: 'CREATE_SUPPORT_TICKET',
    VIEW_TICKETS: 'VIEW_SUPPORT_TICKETS',
    MANAGE_TICKETS: 'MANAGE_SUPPORT_TICKETS'
  },

  // ✅ ADDED: Mobile App Permissions (for your controller)
  MOBILE: {
    VIEW_MOBILE: 'VIEW_MOBILE_APP',
    MANAGE_MOBILE: 'MANAGE_MOBILE_APP',
    APPROVE_MOBILE: 'APPROVE_MOBILE_TRANSACTIONS',
    MOBILE_LOAN_REPAYMENT: 'PROCESS_MOBILE_LOAN_REPAYMENT'
  },

  // ✅ ADDED: Collection Management Permissions (for your Collection model)
  COLLECTION: {
    CREATE: 'CREATE_COLLECTION',
    VIEW: 'VIEW_COLLECTION',
    UPDATE: 'UPDATE_COLLECTION',
    DELETE: 'DELETE_COLLECTION',
    PROCESS: 'PROCESS_COLLECTION',
    VERIFY: 'VERIFY_COLLECTION',
    APPROVE: 'APPROVE_COLLECTION',
    REJECT: 'REJECT_COLLECTION',
    REPORTS: 'VIEW_COLLECTION_REPORTS',
    EXPORT: 'EXPORT_COLLECTION_DATA'
  },

  // ✅ ADDED: Loan Portfolio Permissions (for your LoanPortfolio model)
  LOAN_PORTFOLIO: {
    VIEW: 'VIEW_LOAN_PORTFOLIO',
    MANAGE: 'MANAGE_LOAN_PORTFOLIO',
    UPDATE: 'UPDATE_LOAN_PORTFOLIO',
    REPORTS: 'VIEW_LOAN_PORTFOLIO_REPORTS',
    ANALYTICS: 'VIEW_LOAN_PORTFOLIO_ANALYTICS'
  },

  // ✅ **COMPLETE VAULT MANAGEMENT PERMISSIONS - UPDATED**
  VAULT: {
    // **Vault Operations**
    CREATE_VAULT: 'CREATE_VAULT',
    VIEW_VAULTS: 'VIEW_VAULTS',
    UPDATE_VAULT: 'UPDATE_VAULT',
    DEACTIVATE_VAULT: 'DEACTIVATE_VAULT',
    VIEW_VAULT_STATUS: 'VIEW_VAULT_STATUS',
    OPEN_VAULT: 'OPEN_VAULT',
    CLOSE_VAULT: 'CLOSE_VAULT',
    
    // **Vault Configuration**
    CONFIGURE_VAULT: 'CONFIGURE_VAULT',
    VIEW_VAULT_CONFIG: 'VIEW_VAULT_CONFIG',
    
    // **Access & Authorization**
    MANAGE_VAULT_ACCESS: 'MANAGE_VAULT_ACCESS',
    AUTHORIZE_PERSONNEL: 'AUTHORIZE_PERSONNEL',
    REVOKE_AUTHORIZATION: 'REVOKE_AUTHORIZATION',
    VIEW_AUTHORIZED_PERSONNEL: 'VIEW_AUTHORIZED_PERSONNEL',
    
    // **Approval Workflows**
    CREATE_APPROVAL_REQUEST: 'CREATE_APPROVAL_REQUEST',
    APPROVE_REQUEST: 'APPROVE_REQUEST',
    VIEW_PENDING_APPROVALS: 'VIEW_PENDING_APPROVALS',
    
    // **Security & Maintenance**
    LOG_ACCESS_ATTEMPT: 'LOG_ACCESS_ATTEMPT',
    RECORD_MAINTENANCE: 'RECORD_MAINTENANCE',
    UPDATE_SECURITY_FEATURES: 'UPDATE_SECURITY_FEATURES',
    VIEW_ACCESS_LOGS: 'VIEW_ACCESS_LOGS',
    
    // **Reporting & Analytics**
    VIEW_VAULT_UTILIZATION: 'VIEW_VAULT_UTILIZATION',
    VIEW_SECURITY_COMPLIANCE: 'VIEW_SECURITY_COMPLIANCE',
    VIEW_VAULT_STATISTICS: 'VIEW_VAULT_STATISTICS',
    VIEW_AUDIT_TRAIL: 'VIEW_AUDIT_TRAIL',
    
    // ✅ **BRANCH VAULT MANAGEMENT - ADDED**
    VIEW_BRANCH_VAULTS: 'VIEW_BRANCH_VAULTS',
    MANAGE_BRANCH_VAULTS: 'MANAGE_BRANCH_VAULTS',
    CONFIGURE_BRANCH_VAULT: 'CONFIGURE_BRANCH_VAULT',
    VIEW_BRANCH_VAULT_STATUS: 'VIEW_BRANCH_VAULT_STATUS',
    BRANCH_VAULT_ACCESS: 'MANAGE_BRANCH_VAULT_ACCESS',
    
    // **Financial Operations**
    VAULT_DEPOSIT: 'VAULT_DEPOSIT',
    VAULT_WITHDRAWAL: 'VAULT_WITHDRAWAL',
    VAULT_TRANSFER: 'VAULT_TRANSFER',
    VAULT_RECONCILIATION: 'VAULT_RECONCILIATION',
    VIEW_VAULT_TRANSACTIONS: 'VIEW_VAULT_TRANSACTIONS',
    CANCEL_VAULT_TRANSACTION: 'CANCEL_VAULT_TRANSACTION',
    EXPORT_VAULT_TRANSACTIONS: 'EXPORT_VAULT_TRANSACTIONS',
    
    // **Audit & Compliance**
    VAULT_AUDIT: 'CONDUCT_VAULT_AUDIT',
    VAULT_COMPLIANCE_CHECK: 'PERFORM_VAULT_COMPLIANCE_CHECK',
    GENERATE_VAULT_REPORT: 'GENERATE_VAULT_REPORT',
    
    // **Emergency Operations**
    EMERGENCY_VAULT_ACCESS: 'EMERGENCY_VAULT_ACCESS',
    VAULT_LOCKDOWN: 'INITIATE_VAULT_LOCKDOWN',
    VAULT_ALARM_CONTROL: 'CONTROL_VAULT_ALARM',
    
    // **Key Management**
    MANAGE_VAULT_KEYS: 'MANAGE_VAULT_KEYS',
    ISSUE_TEMP_ACCESS: 'ISSUE_TEMPORARY_ACCESS',
    TRACK_KEY_USAGE: 'TRACK_KEY_USAGE',
    
    // **Capacity Management**
    VIEW_VAULT_CAPACITY: 'VIEW_VAULT_CAPACITY',
    UPDATE_VAULT_CAPACITY: 'UPDATE_VAULT_CAPACITY',
    VAULT_SPACE_ALLOCATION: 'MANAGE_VAULT_SPACE_ALLOCATION',
    
    // **Inventory Management**
    VAULT_INVENTORY_VIEW: 'VIEW_VAULT_INVENTORY',
    VAULT_INVENTORY_UPDATE: 'UPDATE_VAULT_INVENTORY',
    TRACK_VAULT_CONTENTS: 'TRACK_VAULT_CONTENTS',
    
    // **Schedule Management**
    MANAGE_VAULT_SCHEDULE: 'MANAGE_VAULT_SCHEDULE',
    VIEW_VAULT_CALENDAR: 'VIEW_VAULT_CALENDAR',
    SET_VAULT_HOURS: 'SET_VAULT_OPERATING_HOURS',
    
    // **Multi-level Access**
    TIER1_VAULT_ACCESS: 'TIER1_VAULT_ACCESS',
    TIER2_VAULT_ACCESS: 'TIER2_VAULT_ACCESS',
    TIER3_VAULT_ACCESS: 'TIER3_VAULT_ACCESS',
    
    // **Notification & Alerts**
    VAULT_ALERTS: 'VIEW_VAULT_ALERTS',
    CONFIGURE_VAULT_ALERTS: 'CONFIGURE_VAULT_ALERTS',
    ACKNOWLEDGE_VAULT_ALERT: 'ACKNOWLEDGE_VAULT_ALERT',
    
    // **Documentation**
    VAULT_DOCUMENTATION: 'VIEW_VAULT_DOCUMENTATION',
    UPDATE_VAULT_DOCS: 'UPDATE_VAULT_DOCUMENTATION',
    VAULT_POLICIES: 'VIEW_VAULT_POLICIES',
    
    // **Training & Certification**
    VAULT_TRAINING: 'ACCESS_VAULT_TRAINING',
    CERTIFY_PERSONNEL: 'CERTIFY_VAULT_PERSONNEL',
    VIEW_CERTIFICATIONS: 'VIEW_VAULT_CERTIFICATIONS',
  }
};

// ✅ ADDED: Helper function to get all permissions as flat array
export const getAllPermissions = () => {
  const permissions = [];
  
  const traverse = (obj, prefix = '') => {
    for (const key in obj) {
      if (typeof obj[key] === 'object') {
        traverse(obj[key], `${prefix}${key}.`);
      } else {
        permissions.push(obj[key]);
      }
    }
  };
  
  traverse(PERMISSIONS);
  return permissions;
};

// ✅ ADDED: Helper function to check if permission exists
export const hasPermission = (permission, userPermissions = []) => {
  if (!permission) return false;
  
  // Get all permission values as flat array
  const allPermissions = getAllPermissions();
  
  // Check if permission is valid
  const isValidPermission = allPermissions.includes(permission);
  if (!isValidPermission) {
    console.warn(`Permission "${permission}" is not defined in PERMISSIONS object`);
    return false;
  }
  
  // Check if user has permission
  return userPermissions.includes(permission);
};

// ✅ ADDED: Helper function to get permissions by module
export const getPermissionsByModule = (moduleName) => {
  if (!PERMISSIONS[moduleName]) {
    console.warn(`Module "${moduleName}" not found in PERMISSIONS object`);
    return [];
  }
  
  const modulePermissions = [];
  
  const traverse = (obj, prefix = '') => {
    for (const key in obj) {
      if (typeof obj[key] === 'object') {
        traverse(obj[key], `${prefix}${key}.`);
      } else {
        modulePermissions.push(obj[key]);
      }
    }
  };
  
  traverse(PERMISSIONS[moduleName]);
  return modulePermissions;
};

// ✅ ADDED: Get all loan-related permissions including manual repayment
export const getLoanRepaymentPermissions = () => {
  return [
    PERMISSIONS.LOAN_REPAYMENT.MANUAL,
    PERMISSIONS.LOAN_REPAYMENT.PROCESS,
    PERMISSIONS.LOAN_REPAYMENT.VIEW_SCHEDULE,
    PERMISSIONS.LOAN_OPERATIONS.MANUAL_REPAYMENT,
    PERMISSIONS.TRANSACTION.LOAN_REPAYMENT
  ];
};

// ✅ ADDED: Get all bulk repayment permissions
export const getBulkRepaymentPermissions = () => {
  return [
    PERMISSIONS.BULK_OPERATIONS.BULK_LOAN_REPAYMENT,
    PERMISSIONS.BULK_OPERATIONS.BULK_GROUP_REPAYMENT,
    PERMISSIONS.LOAN_OPERATIONS.BULK_REPAYMENT,
    PERMISSIONS.GROUP_LOAN.BULK_REPAYMENT
  ];
};

// ✅ ADDED: Get all group loan permissions
export const getGroupLoanPermissions = () => {
  return [
    PERMISSIONS.GROUP_LOAN.CREATE,
    PERMISSIONS.GROUP_LOAN.VIEW,
    PERMISSIONS.GROUP_LOAN.PROCESS_REPAYMENT,
    PERMISSIONS.GROUP_LOAN.BULK_REPAYMENT,
    PERMISSIONS.GROUP_LOAN.MANAGE_MEMBERS
  ];
};

// ✅ ADDED: Get permissions by controller function
export const getControllerPermissions = () => {
  return {
    // For recordPaymentSimple and recordPayment functions
    SIMPLE_REPAYMENT: [
      PERMISSIONS.LOAN_REPAYMENT.MANUAL,
      PERMISSIONS.LOAN_REPAYMENT.PROCESS,
      PERMISSIONS.LOAN_OPERATIONS.MANUAL_REPAYMENT
    ],
    
    // For processBulkRepayments function - Individual
    BULK_REPAYMENT_INDIVIDUAL: [
      PERMISSIONS.BULK_OPERATIONS.BULK_LOAN_REPAYMENT,
      PERMISSIONS.LOAN_OPERATIONS.BULK_REPAYMENT
    ],
    
    // For processBulkRepayments function - Group
    BULK_REPAYMENT_GROUP: [
      PERMISSIONS.BULK_OPERATIONS.BULK_GROUP_REPAYMENT,
      PERMISSIONS.GROUP_LOAN.BULK_REPAYMENT,
      PERMISSIONS.GROUP_LOAN.PROCESS_REPAYMENT
    ],
    
    // For updateLoanPortfolio function
    LOAN_PORTFOLIO_UPDATE: [
      PERMISSIONS.LOAN_PORTFOLIO.UPDATE,
      PERMISSIONS.LOAN_PORTFOLIO.MANAGE
    ],
    
    // For Collection operations
    COLLECTION_OPERATIONS: [
      PERMISSIONS.COLLECTION.CREATE,
      PERMISSIONS.COLLECTION.PROCESS,
      PERMISSIONS.COLLECTION.APPROVE
    ]
  };
};

// ✅ ADDED: Check if user has any of the required permissions
export const hasAnyPermission = (requiredPermissions, userPermissions = []) => {
  if (!Array.isArray(requiredPermissions) || requiredPermissions.length === 0) {
    return false;
  }
  
  return requiredPermissions.some(permission => 
    userPermissions.includes(permission)
  );
};

// ✅ ADDED: Check if user has all required permissions
export const hasAllPermissions = (requiredPermissions, userPermissions = []) => {
  if (!Array.isArray(requiredPermissions) || requiredPermissions.length === 0) {
    return false;
  }
  
  return requiredPermissions.every(permission => 
    userPermissions.includes(permission)
  );
};

export default PERMISSIONS;