// constants/transactionTypes.js

// Core Banking Transactions
const CORE_TX_TYPES = [
  'DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'DEBIT', 'CREDIT',
  'ADJUSTMENT', 'REVERSAL', 'CHARGE', 'REFUND', 
  'INTEREST_CREDIT', 'DIVIDEND', 'FEE', 'SMS_CHARGE'
];

// Loan Transactions
const LOAN_TX_TYPES = [
  'LOAN_DISBURSEMENT', 'LOAN_REPAYMENT', 'LOAN_INTEREST',
  'LOAN_FEE', 'LOAN_PENALTY', 'LOAN_REFINANCE', 'LOAN_WRITEOFF',
  'LOAN_RECOVERY', 'LOAN_RESCHEDULE', 'LOAN_ADJUSTMENT',
  'LOAN_PROCESSING_FEE', 'LOAN_LIABILITY'
];

// Investment Transactions
const INVESTMENT_TX_TYPES = [
  'INVESTMENT_BUY', 'INVESTMENT_SELL', 'INVESTMENT_DIVIDEND',
  'INVESTMENT_INTEREST', 'INVESTMENT_FEE'
];

// Card Transactions
const CARD_TX_TYPES = [
  'CARD_PURCHASE', 'CARD_CASH_ADVANCE', 'CARD_PAYMENT',
  'CARD_FEE', 'CARD_REWARD', 'CARD_CHARGEBACK'
];

// Digital Transactions
const DIGITAL_TX_TYPES = [
  'MOBILE_PAYMENT', 'ONLINE_TRANSFER', 'BILL_PAYMENT',
  'QR_PAYMENT', 'P2P_TRANSFER'
];

// Special Transaction Types
const SPECIAL_TX_TYPES = [
  'FOREIGN_EXCHANGE', 'BANK_CHARGE', 'TAX_PAYMENT',
  'ESCROW', 'SETTLEMENT', 'CORRESPONDENT',
  'NOSTRO', 'VOSTRO'
];

// Thrift Transactions - MAPPED TO EXISTING ENUM VALUES
const THRIFT_TX_TYPES = {
  OPENING: 'DEPOSIT',
  COLLECTION: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  BANK_PAYMENT: 'TRANSFER',
  THRIFT_OPENING: 'DEPOSIT',
  THRIFT_COLLECTION: 'DEPOSIT',
  THRIFT_WITHDRAWAL: 'WITHDRAWAL'
};

// Processing Fee Transaction
const PROCESSING_FEE_TYPES = ['PROCESSING_FEE'];

// Service Fee Transaction
const SERVICE_FEE_TYPES = ['SERVICE_FEE'];

// General Transaction Types - ACTUAL DATABASE ENUM VALUES
const GENERAL_TX_TYPES = [
  'DEPOSIT',
  'WITHDRAWAL',
  'TRANSFER',
  'LOAN_DISBURSEMENT',
  'LOAN_REPAYMENT',
  'FEE_CHARGE',
  'INTEREST_CREDIT',
  'INTEREST_CHARGE',
  'PENALTY_CHARGE',
  'SALARY_PAYMENT',
  'BILL_PAYMENT',
  'ATM_WITHDRAWAL',
  'ONLINE_TRANSFER',
  'MOBILE_TRANSFER',
  'STANDING_ORDER',
  'DIRECT_DEBIT',
  'CHEQUE_DEPOSIT',
  'CASH_DEPOSIT',
  'CASH_WITHDRAWAL',
  'REVERSAL',
  'ADJUSTMENT',
  'REFUND',
  'THRIFT_OPENING',
  'THRIFT_COLLECTION',
  'THRIFT_WITHDRAWAL',
  'THRIFT_BANK_PAYMENT',
  'SERVICE_FEE',
  'CARD_PURCHASE',
  'SMS_CHARGE',
  'LOAN_INTEREST',
  'LOAN_FEE',
  'LOAN_PENALTY',
  'LOAN_PROCESSING_FEE',
  'INVESTMENT_FEE',
  'CARD_FEE',
  'BANK_CHARGE',
  'LOAN_LIABILITY',
  'LOAN_REFINANCE',
  'LOAN_WRITEOFF',
  'LOAN_RECOVERY',
  'LOAN_RESCHEDULE',
  'LOAN_ADJUSTMENT',
  'INVESTMENT_BUY',
  'INVESTMENT_SELL',
  'INVESTMENT_DIVIDEND',
  'INVESTMENT_INTEREST',
  'CARD_CASH_ADVANCE',
  'CARD_PAYMENT',
  'CARD_REWARD',
  'CARD_CHARGEBACK',
  'MOBILE_PAYMENT',
  'QR_PAYMENT',
  'P2P_TRANSFER',
  'FOREIGN_EXCHANGE',
  'TAX_PAYMENT',
  'ESCROW',
  'SETTLEMENT',
  'CORRESPONDENT',
  'NOSTRO',
  'VOSTRO',
  'PROCESSING_FEE',
  'CHARGE',
  'DIVIDEND',
  'FEE',
  'THRIFT_CYCLE_FEE',
  'THRIFT_CYCLE_INTEREST',
  'THRIFT_CYCLE_PENALTY'
];

// ========== NEW: All charge/fee transaction types (unique) ==========
const CHARGE_TX_TYPES = [
  ...new Set([
    // From core
    'CHARGE', 'FEE', 'SMS_CHARGE',
    // From loan
    'LOAN_FEE', 'LOAN_PENALTY', 'LOAN_PROCESSING_FEE',
    // From investment
    'INVESTMENT_FEE',
    // From card
    'CARD_FEE',
    // From special
    'BANK_CHARGE',
    // Dedicated arrays
    ...PROCESSING_FEE_TYPES,
    ...SERVICE_FEE_TYPES,
    // From general
    'FEE_CHARGE', 'INTEREST_CHARGE', 'PENALTY_CHARGE'
  ])
];

// Helper functions (unchanged)
const getAllTransactionTypes = () => [...GENERAL_TX_TYPES];

const getThriftTransactionType = (thriftType) => {
  const thriftTypeMap = {
    'THRIFT_OPENING': 'DEPOSIT',
    'THRIFT_COLLECTION': 'DEPOSIT',
    'THRIFT_WITHDRAWAL': 'WITHDRAWAL',
    'BANK_PAYMENT': 'TRANSFER'
  };
  return thriftTypeMap[thriftType] || 'DEPOSIT';
};

// Investment & Loan specific (unchanged)
const INVESTMENT_ACCOUNT_TX_TYPES = [
  ...INVESTMENT_TX_TYPES,
  ...GENERAL_TX_TYPES.filter(type =>
    ['TRANSFER', 'DEPOSIT', 'WITHDRAWAL'].includes(type)
  )
];

const LOAN_ACCOUNT_TX_TYPES = [...LOAN_TX_TYPES];

// Export all
export {
  CORE_TX_TYPES,
  LOAN_TX_TYPES,
  INVESTMENT_TX_TYPES,
  CARD_TX_TYPES,
  DIGITAL_TX_TYPES,
  SPECIAL_TX_TYPES,
  THRIFT_TX_TYPES,
  PROCESSING_FEE_TYPES,
  SERVICE_FEE_TYPES,
  INVESTMENT_ACCOUNT_TX_TYPES,
  LOAN_ACCOUNT_TX_TYPES,
  GENERAL_TX_TYPES,
  CHARGE_TX_TYPES,               // ✅ new export
  getAllTransactionTypes,
  getThriftTransactionType
};

// Default export
const allTransactionTypes = {
  CORE_TX_TYPES,
  LOAN_TX_TYPES,
  INVESTMENT_TX_TYPES,
  CARD_TX_TYPES,
  DIGITAL_TX_TYPES,
  SPECIAL_TX_TYPES,
  THRIFT_TX_TYPES,
  PROCESSING_FEE_TYPES,
  SERVICE_FEE_TYPES,
  INVESTMENT_ACCOUNT_TX_TYPES,
  LOAN_ACCOUNT_TX_TYPES,
  GENERAL_TX_TYPES,
  CHARGE_TX_TYPES,
  getAllTransactionTypes,
  getThriftTransactionType
};

export default allTransactionTypes;