import AMLThreshold from '../models/AMLThreshold.js';
import auditLogger from '../utils/AuditLogger.js';  // Fixed: Default import for hybrid logger
import { GENERAL_TX_TYPES } from '../constants/transactionTypes.js';
import { generateTransactionIds } from '../utils/generateAccountNumber.js';

export const createThreshold = async (req, res) => {
  try {
    const { transaction_type, threshold_amount, currency, active, USER_ID } = req.body;

    // Validate transaction type
    if (!GENERAL_TX_TYPES.includes(transaction_type)) {
      return res.status(400).json({ message: 'Invalid transaction type.' });
    }

    // Check if threshold already exists
    const existing = await AMLThreshold.findOne({ transaction_type });
    if (existing) {
      return res.status(400).json({ message: 'Threshold rule already exists for this transaction type.' });
    }

    // Create new threshold rule
    const rule = new AMLThreshold({
      transaction_type,
      threshold_amount,
      currency,
      active,
      threshold_id: generateTransactionIds('THRESHOLD')
    });

    await rule.save();

    const ipAddress = req.ip || req.headers['x-forwarded-for'] || req.connection.remoteAddress;

    // Audit via hybrid logger (event_id auto-generated by pre-save hook)
    auditLogger.info('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: rule._id,
      user_id: USER_ID,
      action: 'CREATE',
      old_value: null,
      new_value: rule.toObject(),  // Includes auto-generated event_id
      ip_address: ipAddress,
      event_type: 'THRESHOLD_CREATE',
      outcome: 'success'
    });

    return res.status(201).json({
      message: 'Threshold rule created successfully',
      data: rule
    });

  } catch (err) {
    console.error('Error in createThreshold:', err);
    // Audit failure (non-blocking)
    auditLogger.error('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: null,
      user_id: req.body.USER_ID || 'system',
      action: 'create_threshold',
      old_value: null,
      new_value: null,
      ip_address: req.ip || 'unknown',
      event_type: 'THRESHOLD_ERROR',
      outcome: 'failure',
      error: err.message
    });
    return res.status(500).json({
      message: 'Failed to create threshold rule',
      error: process.env.NODE_ENV === 'development' ? err.message : undefined
    });
  }
};

// Get all threshold rules (optionally filter by active status)
export const getAllThresholds = async (req, res) => {
  try {
    const { active } = req.query;  // Optional filter
    const filter = active !== undefined ? { active: active === 'true' } : {};
    const rules = await AMLThreshold.find(filter).sort({ created_at: -1 });
    
    const userId = req.user_id || 'system';  // From middleware
    const ipAddress = req.ip_address || '0.0.0.0';

    // Self-audit the query (optional)
    auditLogger.info('Audit Event', {
      entity_type: 'threshold_list_query',
      entity_id: null,
      user_id: userId,
      action: 'get_all_thresholds',
      old_value: null,
      new_value: { count: rules.length, filter: { active } },
      ip_address: ipAddress,
      event_type: 'QUERY_SUCCESS',
      outcome: 'success'
    });

    res.status(200).json(rules);
  } catch (err) {
    console.error('Error fetching all thresholds:', err);
    // Audit failure (non-blocking)
    auditLogger.error('Audit Event', {
      entity_type: 'threshold_list_query',
      entity_id: null,
      user_id: req.user_id || 'system',
      action: 'get_all_thresholds',
      old_value: null,
      new_value: null,
      ip_address: req.ip || 'unknown',
      event_type: 'QUERY_ERROR',
      outcome: 'failure',
      error: err.message
    });
    res.status(500).json({ message: 'Failed to retrieve thresholds', error: err.message });
  }
};

// Get threshold by transaction type
export const getThresholdByType = async (req, res) => {
  try {
    const { type } = req.params;
    const userId = req.user_id || 'system';  // From middleware
    const ipAddress = req.ip_address || '0.0.0.0';

    const rule = await AMLThreshold.findOne({ transaction_type: type });
    if (!rule) {
      // Self-audit not-found (optional)
      auditLogger.info('Audit Event', {
        entity_type: 'threshold_query',
        entity_id: type,
        user_id: userId,
        action: 'get_threshold_by_type',
        old_value: null,
        new_value: { status: 'not_found' },
        ip_address: ipAddress,
        event_type: 'QUERY_NOT_FOUND',
        outcome: 'failure'
      });
      return res.status(404).json({ message: 'No threshold found for this type' });
    }

    // Self-audit success (optional)
    auditLogger.info('Audit Event', {
      entity_type: 'threshold_query',
      entity_id: type,
      user_id: userId,
      action: 'get_threshold_by_type',
      old_value: null,
      new_value: { event_id: rule.event_id },
      ip_address: ipAddress,
      event_type: 'QUERY_SUCCESS',
      outcome: 'success'
    });

    res.status(200).json(rule);
  } catch (err) {
    console.error('Error retrieving threshold:', err);
    // Audit failure (non-blocking)
    auditLogger.error('Audit Event', {
      entity_type: 'threshold_query',
      entity_id: req.params.type || null,
      user_id: req.user_id || 'system',
      action: 'get_threshold_by_type',
      old_value: null,
      new_value: null,
      ip_address: req.ip || 'unknown',
      event_type: 'QUERY_ERROR',
      outcome: 'failure',
      error: err.message
    });
    res.status(500).json({ message: 'Error retrieving threshold', error: err.message });
  }
};

// Update a threshold rule
export const updateThreshold = async (req, res) => {
  try {
    const { transaction_type } = req.params;
    const updates = req.body;
    const USER_ID = req.body.USER_ID || req.user_id || 'system';  // From body or middleware
    const ipAddress = req.ip || req.headers['x-forwarded-for'] || req.connection.remoteAddress;

    // Optional: Validate required fields
    if (!transaction_type) {
      return res.status(400).json({ message: 'transaction_type is required in URL' });
    }

    if (!updates || typeof updates !== 'object') {
      return res.status(400).json({ message: 'Update payload is required' });
    }

    // Fetch existing for old_value
    const existing = await AMLThreshold.findOne({ transaction_type });
    if (!existing) {
      return res.status(404).json({ message: `No threshold rule found for transaction_type: ${transaction_type}` });
    }

    const oldValue = JSON.stringify(existing);

    // Perform update
    const rule = await AMLThreshold.findOneAndUpdate(
      { transaction_type },
      {
        $set: {
          ...updates,
          updated_at: new Date()
        }
      },
      { new: true }
    );

    // Audit via hybrid logger
    auditLogger.info('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: rule._id,
      user_id: USER_ID,
      action: 'UPDATE',
      old_value: oldValue,
      new_value: JSON.stringify(rule),
      ip_address: ipAddress,
      event_type: 'THRESHOLD_UPDATE',
      outcome: 'success'
    });

    return res.status(200).json({
      message: 'Threshold successfully updated',
      data: rule
    });
  } catch (error) {
    console.error('Update Threshold Error:', error);
    // Audit failure (non-blocking)
    auditLogger.error('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: req.params.transaction_type || null,
      user_id: req.body.USER_ID || 'system',
      action: 'update_threshold',
      old_value: null,
      new_value: null,
      ip_address: req.ip || 'unknown',
      event_type: 'THRESHOLD_ERROR',
      outcome: 'failure',
      error: error.message
    });
    return res.status(500).json({
      message: 'An error occurred while updating the threshold',
      error: error.message
    });
  }
};

// Delete a threshold rule (optional: implement soft delete)
export const deleteThreshold = async (req, res) => {
  try {
    const { transaction_type } = req.params;
    const USER_ID = req.body.USER_ID || req.user_id || 'system';  // From body or middleware
    const ipAddress = req.ip || req.headers['x-forwarded-for'] || req.connection.remoteAddress;

    const rule = await AMLThreshold.findOneAndDelete({ transaction_type });

    if (!rule) {
      // Self-audit not-found (optional)
      auditLogger.info('Audit Event', {
        entity_type: 'THRESHOLD_RULE',
        entity_id: transaction_type,
        user_id: USER_ID,
        action: 'DELETE',
        old_value: null,
        new_value: { status: 'not_found' },
        ip_address: ipAddress,
        event_type: 'DELETE_NOT_FOUND',
        outcome: 'failure'
      });
      return res.status(404).json({ message: 'Threshold not found for this transaction_type' });
    }

    const oldValue = JSON.stringify(rule);

    // Audit deletion via hybrid logger
    auditLogger.info('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: rule._id,
      user_id: USER_ID,
      action: 'DELETE',
      old_value: oldValue,
      new_value: null,
      ip_address: ipAddress,
      event_type: 'THRESHOLD_DELETE',
      outcome: 'success'
    });

    res.status(200).json({ message: 'Threshold rule deleted' });
  } catch (err) {
    console.error('Error deleting threshold:', err);
    // Audit failure (non-blocking)
    auditLogger.error('Audit Event', {
      entity_type: 'THRESHOLD_RULE',
      entity_id: req.params.transaction_type || null,
      user_id: req.body.USER_ID || 'system',
      action: 'delete_threshold',
      old_value: null,
      new_value: null,
      ip_address: req.ip || 'unknown',
      event_type: 'DELETE_ERROR',
      outcome: 'failure',
      error: err.message
    });
    res.status(500).json({ message: 'Failed to delete threshold', error: err.message });
  }
};