import mongoose from 'mongoose';
import GLAccount from '../models/GLAccount.js';

async function initializeGLAccounts() {
  try {
    await mongoose.connect('mongodb+srv://Administrator:Fo%24th3DR%24%3D083@cluster0.zpuy3.mongodb.net/evolution_banking?retryWrites=true&w=majority');

    // Clear existing data (remove in production)
    await GLAccount.deleteMany({});
    console.log('Cleared existing GL accounts');

    // Step 1: Insert top-level accounts (ASSET, LIABILITY, etc.)
    const topLevelAccounts = [
      {
        GL_ACCT_NO: "01-000-000-001-000-000",
        GL_ACCT_ID: "0000001",
        CREATED_BY: "PCO06",
        categoryCode: "1",
        categoryName: "ASSET",
        parentCode: null,
        level: 1,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "0",
        subfolderId: "0",
        BAL_CD: "10",
        SUB_LEDGER_NO: "000",
        BU_ID: "000",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Top-Level Asset Account",
        GL_ACCT_CAT: "1",
        JOURNAL_ID: "839748405678",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "0",
        SEG_DESC: "",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-000-000-001-000-000",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-000-000-002-000-000",
        GL_ACCT_ID: "0000002",
        CREATED_BY: "PCO06",
        categoryCode: "2",
        categoryName: "LIABILITY",
        parentCode: null,
        level: 1,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "0",
        subfolderId: "0",
        BAL_CD: "20",
        SUB_LEDGER_NO: "000",
        BU_ID: "000",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Top-Level Liability Account",
        GL_ACCT_CAT: "2",
        JOURNAL_ID: "839748405679",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "0",
        SEG_DESC: "",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "02-000-000-002-000-000",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "04-000-000-004-000-000",
        GL_ACCT_ID: "0000003",
        CREATED_BY: "PCO06",
        categoryCode: "4",
        categoryName: "INCOME",
        parentCode: null,
        level: 1,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "0",
        subfolderId: "0",
        BAL_CD: "40",
        SUB_LEDGER_NO: "000",
        BU_ID: "000",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Top-Level Income Account",
        GL_ACCT_CAT: "4",
        JOURNAL_ID: "839748405680",
        TRANSACTION_TYPE: "Income Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "0",
        SEG_DESC: "",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "04-000-000-004-000-000",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "05-000-000-005-000-000",
        GL_ACCT_ID: "0000004",
        CREATED_BY: "PCO06",
        categoryCode: "5",
        categoryName: "EXPENSES",
        parentCode: null,
        level: 1,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "0",
        subfolderId: "0",
        BAL_CD: "50",
        SUB_LEDGER_NO: "000",
        BU_ID: "000",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Top-Level Expenses Account",
        GL_ACCT_CAT: "5",
        JOURNAL_ID: "839748405681",
        TRANSACTION_TYPE: "Expense Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "0",
        SEG_DESC: "",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "05-000-000-005-000-000",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "06-000-000-006-000-000",
        GL_ACCT_ID: "0000005",
        CREATED_BY: "PCO06",
        categoryCode: "6",
        categoryName: "CONTINGENT-ASSETS",
        parentCode: null,
        level: 1,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "0",
        subfolderId: "0",
        BAL_CD: "60",
        SUB_LEDGER_NO: "000",
        BU_ID: "000",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Top-Level Contingent Assets Account",
        GL_ACCT_CAT: "6",
        JOURNAL_ID: "839748405682",
        TRANSACTION_TYPE: "Contingent Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "0",
        SEG_DESC: "",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "06-000-000-006-000-000",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ];

    for (const account of topLevelAccounts) {
      await GLAccount.create(account);
      console.log(`Top-level account inserted: ${account.GL_ACCT_NO} (${account.categoryName})`);
    }

    // Step 2: Insert sub-level accounts for loan product
    const subLevelAccounts = [
      {
        GL_ACCT_NO: "01-010-111-105-102-100",
        GL_ACCT_ID: "0000010",
        CREATED_BY: "PCO06",
        categoryCode: "105",
        categoryName: "LOANS AND OVERDRAFTS TO CLIENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "111",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Principal Loan Account",
        GL_ACCT_CAT: "105",
        JOURNAL_ID: "839748405683",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Principal Loan Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-112-105-102-101",
        GL_ACCT_ID: "0000011",
        CREATED_BY: "PCO06",
        categoryCode: "105",
        categoryName: "LOANS AND OVERDRAFTS TO CLIENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "112",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Account for Individual Loan",
        GL_ACCT_CAT: "105",
        JOURNAL_ID: "839748405684",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Account for Individual Loan",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "05-010-113-504-102-102",
        GL_ACCT_ID: "0000012",
        CREATED_BY: "PCO06",
        categoryCode: "504",
        categoryName: "LOAN WRITE OFFS",
        parentCode: "5",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "5",
        subfolderId: "1",
        BAL_CD: "50",
        SUB_LEDGER_NO: "113",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Charge-Off Account",
        GL_ACCT_CAT: "504",
        JOURNAL_ID: "839748405685",
        TRANSACTION_TYPE: "Expense Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Charge-Off Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-114-106-102-103",
        GL_ACCT_ID: "0000013",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "114",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Loan Charge Receivable Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405686",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Loan Charge Receivable Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "06-010-115-601-102-104",
        GL_ACCT_ID: "0000014",
        CREATED_BY: "PCO06",
        categoryCode: "601",
        categoryName: "CONTINGENT ASSETS",
        parentCode: "6",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "6",
        subfolderId: "1",
        BAL_CD: "60",
        SUB_LEDGER_NO: "115",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Contingent Account",
        GL_ACCT_CAT: "601",
        JOURNAL_ID: "839748405687",
        TRANSACTION_TYPE: "Contingent Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Contingent Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-116-106-102-105",
        GL_ACCT_ID: "0000015",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "116",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Delinquent Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405688",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Delinquent Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "04-010-117-401-102-106",
        GL_ACCT_ID: "0000016",
        CREATED_BY: "PCO06",
        categoryCode: "401",
        categoryName: "INTEREST INCOME ON LOANS",
        parentCode: "4",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "4",
        subfolderId: "1",
        BAL_CD: "40",
        SUB_LEDGER_NO: "117",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Income Account",
        GL_ACCT_CAT: "401",
        JOURNAL_ID: "839748405689",
        TRANSACTION_TYPE: "Income Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Income Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-118-107-102-107",
        GL_ACCT_ID: "0000017",
        CREATED_BY: "PCO06",
        categoryCode: "107",
        categoryName: "ACCRUED INTEREST RECEIVABLE ON OVERDRAFT AND LOANS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "118",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Receivable Account",
        GL_ACCT_CAT: "107",
        JOURNAL_ID: "839748405690",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Receivable Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-010-119-206-102-108",
        GL_ACCT_ID: "0000018",
        CREATED_BY: "PCO06",
        categoryCode: "206",
        categoryName: "SUSPENDED INTEREST INCOME",
        parentCode: "2",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "2",
        subfolderId: "1",
        BAL_CD: "20",
        SUB_LEDGER_NO: "119",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Suspense Account",
        GL_ACCT_CAT: "206",
        JOURNAL_ID: "839748405691",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: true,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Suspense Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-010-120-206-102-109",
        GL_ACCT_ID: "0000019",
        CREATED_BY: "PCO06",
        categoryCode: "206",
        categoryName: "SUSPENDED INTEREST INCOME",
        parentCode: "2",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "2",
        subfolderId: "1",
        BAL_CD: "20",
        SUB_LEDGER_NO: "120",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Late Fee Suspense Account",
        GL_ACCT_CAT: "206",
        JOURNAL_ID: "839748405692",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: true,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Late Fee Suspense Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-121-106-102-110",
        GL_ACCT_ID: "0000020",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "121",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Maturity Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405693",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Maturity Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-122-106-102-111",
        GL_ACCT_ID: "0000021",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "122",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Non-Accrual Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405694",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Non-Accrual Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-010-123-206-102-112",
        GL_ACCT_ID: "0000022",
        CREATED_BY: "PCO06",
        categoryCode: "206",
        categoryName: "SUSPENDED INTEREST INCOME",
        parentCode: "2",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "2",
        subfolderId: "1",
        BAL_CD: "20",
        SUB_LEDGER_NO: "123",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Non-Accrual Interest Offset Account",
        GL_ACCT_CAT: "206",
        JOURNAL_ID: "839748405695",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Non-Accrual Interest Offset Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-124-107-102-113",
        GL_ACCT_ID: "0000023",
        CREATED_BY: "PCO06",
        categoryCode: "107",
        categoryName: "ACCRUED INTEREST RECEIVABLE ON OVERDRAFT AND LOANS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "124",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Non-Accrual Interest Receivable Account",
        GL_ACCT_CAT: "107",
        JOURNAL_ID: "839748405696",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Non-Accrual Interest Receivable Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "05-010-125-503-102-114",
        GL_ACCT_ID: "0000024",
        CREATED_BY: "PCO06",
        categoryCode: "503",
        categoryName: "LOAN LOSS PROVISION EXPENSE ACCOUNTS",
        parentCode: "5",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "5",
        subfolderId: "1",
        BAL_CD: "50",
        SUB_LEDGER_NO: "125",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Provision Reserve Account",
        GL_ACCT_CAT: "503",
        JOURNAL_ID: "839748405697",
        TRANSACTION_TYPE: "Expense Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Provision Reserve Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "05-010-126-503-102-115",
        GL_ACCT_ID: "0000025",
        CREATED_BY: "PCO06",
        categoryCode: "503",
        categoryName: "LOAN LOSS PROVISION EXPENSE ACCOUNTS",
        parentCode: "5",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "5",
        subfolderId: "1",
        BAL_CD: "50",
        SUB_LEDGER_NO: "126",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Provision Expense Account",
        GL_ACCT_CAT: "503",
        JOURNAL_ID: "839748405698",
        TRANSACTION_TYPE: "Expense Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Provision Expense Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "04-010-127-402-102-116",
        GL_ACCT_ID: "0000026",
        CREATED_BY: "PCO06",
        categoryCode: "402",
        categoryName: "PENALTY AND FEES INCOME",
        parentCode: "4",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "4",
        subfolderId: "1",
        BAL_CD: "40",
        SUB_LEDGER_NO: "127",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Recoveries Account",
        GL_ACCT_CAT: "402",
        JOURNAL_ID: "839748405699",
        TRANSACTION_TYPE: "Income Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Recoveries Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-128-106-102-117",
        GL_ACCT_ID: "0000027",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "128",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Repayment Control Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405700",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: true,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Repayment Control Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-010-129-206-102-118",
        GL_ACCT_ID: "0000028",
        CREATED_BY: "PCO06",
        categoryCode: "206",
        categoryName: "SUSPENDED INTEREST INCOME",
        parentCode: "2",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "2",
        subfolderId: "1",
        BAL_CD: "20",
        SUB_LEDGER_NO: "129",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Loan Suspense Account",
        GL_ACCT_CAT: "206",
        JOURNAL_ID: "839748405701",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: true,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Loan Suspense Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-130-106-102-119",
        GL_ACCT_ID: "0000029",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "130",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Unapplied Funds Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405702",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Unapplied Funds Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "01-010-131-106-102-120",
        GL_ACCT_ID: "0000030",
        CREATED_BY: "PCO06",
        categoryCode: "106",
        categoryName: "RECEIVABLE AND REPAYMENTS",
        parentCode: "1",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "1",
        subfolderId: "1",
        BAL_CD: "10",
        SUB_LEDGER_NO: "131",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Uncleared Balance Account",
        GL_ACCT_CAT: "106",
        JOURNAL_ID: "839748405703",
        TRANSACTION_TYPE: "Asset Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Uncleared Balance Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "02-010-132-206-102-121",
        GL_ACCT_ID: "0000031",
        CREATED_BY: "PCO06",
        categoryCode: "206",
        categoryName: "SUSPENDED INTEREST INCOME",
        parentCode: "2",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "2",
        subfolderId: "1",
        BAL_CD: "20",
        SUB_LEDGER_NO: "132",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Unearned Interest Account",
        GL_ACCT_CAT: "206",
        JOURNAL_ID: "839748405704",
        TRANSACTION_TYPE: "Liability Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Unearned Interest Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "04-010-133-401-102-122",
        GL_ACCT_ID: "0000032",
        CREATED_BY: "PCO06",
        categoryCode: "401",
        categoryName: "INTEREST INCOME ON LOANS",
        parentCode: "4",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "4",
        subfolderId: "1",
        BAL_CD: "40",
        SUB_LEDGER_NO: "133",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Credit Account",
        GL_ACCT_CAT: "401",
        JOURNAL_ID: "839748405705",
        TRANSACTION_TYPE: "Income Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Credit Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        GL_ACCT_NO: "05-010-134-501-102-123",
        GL_ACCT_ID: "0000033",
        CREATED_BY: "PCO06",
        categoryCode: "501",
        categoryName: "INTEREST EXPENSE",
        parentCode: "5",
        level: 2,
        organizationName: "PCO BANK",
        departmentName: "FINANCE",
        LEDGER_NO: 100,
        PARENT_ID: "5",
        subfolderId: "1",
        BAL_CD: "50",
        SUB_LEDGER_NO: "134",
        BU_ID: "102",
        SEG_NO: 1,
        CHART_OF_ACCT_ID: "1",
        ACCT_DESC: "Interest Debit Account",
        GL_ACCT_CAT: "501",
        JOURNAL_ID: "839748405706",
        TRANSACTION_TYPE: "Expense Balance",
        CR_ALLOWED: true,
        DR_ALLOWED: true,
        REC_ST: "Active",
        POST_ALLOW: true,
        POST_FG: false,
        CONTROL_ACCT_FG: false,
        SUSPENSE_ACCT_FG: false,
        ALLOW_BAL_SWING_FG: false,
        SEG_VALUE: "12",
        SEG_DESC: "Interest Debit Account",
        SEG_TY_CD: "",
        SEG_PLACEHLDR_ID: "",
        DELAY_GL_POSTING: false,
        LEDGER_BALANCE: 0,
        CURRENCY_CODE: "NGN",
        transactions: [],
        SETTLEMENT_GL_ACCT_NO: "01-010-111-105-102-100",
        createdAt: new Date(),
        updatedAt: new Date()
      }
    ];

    for (const account of subLevelAccounts) {
      await GLAccount.create(account);
      console.log(`Account inserted: ${account.GL_ACCT_NO} (${account.categoryName})`);
    }

    console.log('GL Accounts initialized');
    await mongoose.disconnect();
  } catch (error) {
    console.error('Error initializing GL accounts:', error);
    await mongoose.disconnect();
  }
}

initializeGLAccounts();