// -- ============================================
// -- ROLES TABLE - COMPLETE WITH ALL PERMISSIONS
// -- ============================================

// -- Drop table if exists (BE CAREFUL - only use if you want to reset)
// -- DROP TABLE IF EXISTS roles;

// CREATE TABLE IF NOT EXISTS roles (
//     role_id INT PRIMARY KEY AUTO_INCREMENT,
//     role_name VARCHAR(100) NOT NULL,
//     code VARCHAR(50) NOT NULL UNIQUE,
//     description TEXT,
//     permissions JSON,
//     active BOOLEAN DEFAULT TRUE,
//     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
//     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
//     INDEX idx_active (active),
//     INDEX idx_code (code)
// ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

// -- ============================================
// -- INSERT DEFAULT ROLES WITH COMPLETE PERMISSIONS
// -- ============================================

// -- 1. Administrator - Full system access (ALL PERMISSIONS)
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Administrator', 'ADMIN', 'Full system access with all permissions',
//  JSON_ARRAY(
//    -- Core Transaction Permissions
//    'VIEW_DRAWER', 'MANAGE_DRAWER', 'RECONCILE_DRAWER',
   
//    -- Customer Management
//    'CREATE_CUSTOMER', 'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'DELETE_CUSTOMER',
//    'VERIFY_KYC', 'CUSTOMER_IDENTIFICATION', 'VIEW_CUSTOMER_PROFILE', 'CUSTOMER_APPROVAL',
   
//    -- Account Operations
//    'OPEN_ACCOUNT', 'CLOSE_ACCOUNT', 'FREEZE_ACCOUNT', 'VIEW_ACCOUNT_BALANCE',
//    'VIEW_ACCOUNT_STATEMENT', 'DEPOSIT_101', 'WITHDRAWAL_102', 'UPDATE_ACCOUNT',
//    'CREATE_TERM_DEPOSIT',
   
//    -- Loan Operations
//    'DISBURSE_LOAN', 'APPROVE_LOAN', 'REJECT_LOAN', 'RESTRUCTURE_LOAN',
//    'WRITE_OFF_LOAN', 'COLLECT_LOAN', 'RECOVER_LOAN', 'CREATE_LOAN_CONTRACT',
//    'VIEW_LOAN', 'PROCESS_LOAN', 'CREATE_LOAN_CREDIT_APPLICATION',
//    'PROCESS_MANUAL_LOAN_REPAYMENT', 'PROCESS_BULK_LOAN_REPAYMENTS',
   
//    -- Loan Repayment
//    'MANUAL_LOAN_REPAYMENT', 'PROCESS_LOAN_REPAYMENT', 'VIEW_LOAN_REPAYMENT_SCHEDULE',
//    'OVERRIDE_LOAN_REPAYMENT', 'PROCESS_PARTIAL_REPAYMENT', 'PROCESS_ADVANCE_REPAYMENT',
//    'RESCHEDULE_REPAYMENT', 'REVERSE_LOAN_REPAYMENT', 'VIEW_REPAYMENT_HISTORY',
//    'PRINT_REPAYMENT_RECEIPT', 'EXPORT_REPAYMENT_DATA', 'RECONCILE_REPAYMENT',
//    'PROCESS_BULK_LOAN_REPAYMENTS',
   
//    -- Group Loan
//    'CREATE_GROUP_LOAN', 'VIEW_GROUP_LOAN', 'UPDATE_GROUP_LOAN', 'DISBURSE_GROUP_LOAN',
//    'APPROVE_GROUP_LOAN', 'REJECT_GROUP_LOAN', 'MANAGE_GROUP_LOAN_MEMBERS',
//    'PROCESS_GROUP_LOAN_REPAYMENT', 'VIEW_GROUP_LOAN_SCHEDULE',
//    'PROCESS_BULK_GROUP_LOAN_REPAYMENT', 'COLLECT_GROUP_SAVINGS',
//    'VIEW_GROUP_LOAN_REPORTS', 'EXPORT_GROUP_LOAN_DATA', 'VIEW_GROUP_LOAN_AUDIT',
   
//    -- Loan Fees
//    'CREATE_LOAN_FEE', 'VIEW_LOAN_FEES', 'UPDATE_LOAN_FEE', 'TOGGLE_LOAN_FEE_STATUS',
//    'WAIVE_LOAN_FEE', 'SETUP_LOAN_FEE',
   
//    -- Credit Application
//    'CREATE_CREDIT_APP', 'REVIEW_CREDIT_APP', 'APPROVE_CREDIT_APP', 'REJECT_CREDIT_APP',
   
//    -- Financial Posting
//    'CUSTOMER_POSTING', 'GL_POSTING', 'REVERSE_TRANSACTION', 'ADJUST_TRANSACTION',
//    'VIEW_CHART_OF_ACCOUNT', 'VIEW_GL_SUBFOLDER', 'VIEW_SUBFOLDER_ACCOUNT',
//    'MANAGE_DEPARTMENT',
   
//    -- Transactions
//    'MAKE_DEPOSIT', 'MAKE_WITHDRAWAL', 'INITIATE_TRANSFER', 'INTERNAL_TRANSFER',
//    'EXTERNAL_TRANSFER', 'PROCESS_BULK_TRANSACTIONS', 'VIEW_TRANSACTION_HISTORY',
//    'CANCEL_TRANSACTION', 'APPROVE_TRANSACTION', 'REJECT_TRANSACTION',
//    'MAKE_OPENING_DEPOSIT', 'PROCESS_GL_TO_GL', 'PROCESS_CREDIT_GL',
//    'PROCESS_DEBIT_GL', 'REPRINT_TRANSACTION_RECEIPT', 'VIEW_RECENT_TRANSACTIONS',
//    'VIEW_TRANSACTION_STATS', 'PROCESS_LOAN_REPAYMENT_TRANSACTION',
   
//    -- Deposit Management
//    'CREATE_DEPOSIT', 'CREATE_DEPOSIT_APPLICATION', 'VIEW_DEPOSIT_DETAILS',
//    'DEPOSIT_APPLICATION_APPROVAL',
   
//    -- Treasury
//    'TREASURY_VIEW', 'TREASURY_MANAGE', 'TREASURY_APPROVE',
   
//    -- VAULT - COMPLETE SET
//    'CREATE_VAULT', 'VIEW_VAULTS', 'UPDATE_VAULT', 'DEACTIVATE_VAULT',
//    'VIEW_VAULT_STATUS', 'OPEN_VAULT', 'CLOSE_VAULT', 'VIEW_VAULT_CONFIG',
//    'CONFIGURE_VAULT', 'MANAGE_VAULT_ACCESS', 'AUTHORIZE_PERSONNEL',
//    'REVOKE_AUTHORIZATION', 'VIEW_AUTHORIZED_PERSONNEL', 'CREATE_APPROVAL_REQUEST',
//    'APPROVE_REQUEST', 'VIEW_PENDING_APPROVALS', 'LOG_ACCESS_ATTEMPT',
//    'RECORD_MAINTENANCE', 'UPDATE_SECURITY_FEATURES', 'VIEW_ACCESS_LOGS',
//    'VIEW_VAULT_UTILIZATION', 'VIEW_SECURITY_COMPLIANCE', 'VIEW_VAULT_STATISTICS',
//    'VIEW_AUDIT_TRAIL', 'VIEW_BRANCH_VAULTS', 'MANAGE_BRANCH_VAULTS',
//    'CONFIGURE_BRANCH_VAULT', 'VIEW_BRANCH_VAULT_STATUS', 'MANAGE_BRANCH_VAULT_ACCESS',
//    'VAULT_DEPOSIT', 'VAULT_WITHDRAWAL', 'VAULT_TRANSFER', 'VAULT_RECONCILIATION',
//    'VIEW_VAULT_TRANSACTIONS', 'CANCEL_VAULT_TRANSACTION', 'EXPORT_VAULT_TRANSACTIONS',
//    'CONDUCT_VAULT_AUDIT', 'PERFORM_VAULT_COMPLIANCE_CHECK', 'GENERATE_VAULT_REPORT',
//    'EMERGENCY_VAULT_ACCESS', 'INITIATE_VAULT_LOCKDOWN', 'CONTROL_VAULT_ALARM',
//    'MANAGE_VAULT_KEYS', 'ISSUE_TEMPORARY_ACCESS', 'TRACK_KEY_USAGE',
//    'VIEW_VAULT_CAPACITY', 'UPDATE_VAULT_CAPACITY', 'MANAGE_VAULT_SPACE_ALLOCATION',
//    'VIEW_VAULT_INVENTORY', 'UPDATE_VAULT_INVENTORY', 'TRACK_VAULT_CONTENTS',
//    'MANAGE_VAULT_SCHEDULE', 'VIEW_VAULT_CALENDAR', 'SET_VAULT_OPERATING_HOURS',
//    'TIER1_VAULT_ACCESS', 'TIER2_VAULT_ACCESS', 'TIER3_VAULT_ACCESS',
//    'VIEW_VAULT_ALERTS', 'CONFIGURE_VAULT_ALERTS', 'ACKNOWLEDGE_VAULT_ALERT',
//    'VIEW_VAULT_DOCUMENTATION', 'UPDATE_VAULT_DOCUMENTATION', 'VIEW_VAULT_POLICIES',
//    'ACCESS_VAULT_TRAINING', 'CERTIFY_VAULT_PERSONNEL', 'VIEW_VAULT_CERTIFICATIONS',
   
//    -- Reports
//    'VIEW_REPORTS', 'EXPORT_REPORTS', 'VIEW_CUSTOMER_REPORT',
//    'VIEW_TERM_DEPOSIT_REPORT', 'VIEW_ACCOUNT_STATEMENT_REPORT',
//    'VIEW_TRIAL_BALANCE_REPORT', 'VIEW_INCOME_EXPENSE_REPORT', 'VIEW_ALL_REPORTS',
//    'VIEW_TELLER_SUMMARY_REPORT', 'VIEW_GUARANTOR_REPORT', 'VIEW_PERFORMANCE_METRICS',
//    'VIEW_LOAN_REPAYMENT_REPORT', 'VIEW_GROUP_LOAN_REPORT', 'VIEW_BULK_REPAYMENT_REPORT',
//    'GENERATE_REPORTS', 'CREATE_CUSTOM_REPORTS',
   
//    -- Analytics
//    'VIEW_BUSINESS_ANALYTICS', 'EXPORT_ANALYTICS_DATA', 'VIEW_TELLER_ANALYTICS',
//    'VIEW_LOAN_REPAYMENT_ANALYTICS',
   
//    -- Performance
//    'VIEW_PERFORMANCE_METRICS', 'VIEW_TELLER_PERFORMANCE', 'VIEW_BRANCH_PERFORMANCE',
//    'EXPORT_PERFORMANCE_DATA', 'VIEW_LOAN_REPAYMENT_PERFORMANCE',
   
//    -- Statistics
//    'VIEW_REAL_TIME_STATISTICS', 'VIEW_HISTORICAL_STATISTICS',
//    'VIEW_FINANCIAL_STATISTICS', 'VIEW_OPERATIONAL_STATISTICS',
   
//    -- System Administration
//    'MANAGE_USERS', 'ACTIVATE_USER', 'DEACTIVATE_USER', 'CREATE_USER',
//    'UPDATE_USER', 'VIEW_USERS', 'RESET_PASSWORD', 'VIEW_AUDIT_LOGS',
//    'MANAGE_SYSTEM_CONFIG', 'SYSTEM_BACKUP', 'SYSTEM_RESTORE', 'VIEW_SYSTEM_DATE',
//    'TRIGGER_OS_OPERATIONS', 'VIEW_LICENSE_DETAILS', 'CONFIGURE_LOAN_REPAYMENT',
   
//    -- Permission Management
//    'CREATE_PERMISSION', 'VIEW_PERMISSIONS', 'UPDATE_PERMISSIONS', 'ASSIGN_ROLES',
//    'CLONE_ROLE_PERMISSIONS', 'MANAGE_BUSINESS_ROLE', 'VIEW_BUSINESS_ROLE_LIST',
//    'CREATE_BUSINESS_ROLE', 'VIEW_BUSINESS_ROLE_QUEUE', 'SETUP_BUSINESS_ROLE_QUEUE',
   
//    -- Security Profile
//    'ADD_USER', 'ASSIGN_USER_ROLE', 'ASSIGN_CSO_RIGHT', 'RESET_PASSWORD',
//    'VIEW_SECURITY_CONSOLE',
   
//    -- User Management
//    'MANAGE_USERS_MODULE', 'ACTIVATE_USER', 'DEACTIVATE_USER', 'CREATE_USER',
//    'UPDATE_USER', 'VIEW_USERS', 'DELETE_USER', 'RESET_USER_PASSWORD',
//    'ASSIGN_USER_ROLES', 'VIEW_USER_PROFILE', 'EXPORT_USER_DATA',
   
//    -- Approvals
//    'APPROVE_FINANCIAL', 'APPROVE_TRANSACTION', 'APPROVE_CUSTOMER_ACTION',
//    'APPROVE_LOAN', 'MANAGER_APPROVAL', 'APPROVE_CASH_DEPOSIT',
//    'APPROVE_GL_TRANSACTION', 'APPROVE_GUARANTOR', 'DEPOSIT_APPLICATION_APPROVAL',
//    'APPROVE_STANDING_ORDER', 'APPROVE_USER_ACTIVATION', 'APPROVE_VAULT_ACCESS',
//    'APPROVE_VAULT_OPERATION', 'APPROVE_LOAN_REPAYMENT', 'APPROVE_GROUP_LOAN',
//    'APPROVE_BULK_REPAYMENT',
   
//    -- Workflow
//    'CONFIGURE_WORKFLOW', 'MANAGE_WORKFLOW_SUBPROCESS', 'WORKFLOW.VIEW',
//    'MANAGE_LOAN_REPAYMENT_WORKFLOW', 'MANAGE_GROUP_LOAN_WORKFLOW',
   
//    -- Operations
//    'OPERATIONS_VIEW', 'OPERATIONS_MANAGE', 'OPERATIONS_APPROVE',
//    'OPERATIONS_LOAN_REPAYMENT',
   
//    -- Bulk Operations
//    'PROCESS_BULK_OPERATIONS', 'UPLOAD_BULK_DATA', 'DOWNLOAD_BULK_TEMPLATES',
//    'VALIDATE_BULK_DATA', 'EXECUTE_BULK_OPERATIONS',
//    'PROCESS_BULK_LOAN_REPAYMENTS', 'PROCESS_BULK_GROUP_REPAYMENTS',
//    'IMPORT_BULK_CSV_DATA', 'EXPORT_BULK_CSV_DATA',
   
//    -- Print & Export
//    'PRINT_RECEIPT', 'PRINT_REPORT', 'EXPORT_CSV', 'EXPORT_PDF', 'EXPORT_EXCEL',
//    'PRINT_LOAN_REPAYMENT_RECEIPT', 'PRINT_BULK_REPAYMENT_RECEIPT',
//    'EXPORT_BULK_REPAYMENT_DATA',
   
//    -- Queue Management
//    'VIEW_QUEUE', 'MANAGE_QUEUE', 'PROCESS_QUEUE_ITEMS', 'REORDER_QUEUE',
//    'CLEAR_QUEUE', 'MANAGE_LOAN_REPAYMENT_QUEUE', 'MANAGE_BULK_REPAYMENT_QUEUE',
   
//    -- AML
//    'VIEW_AML_THRESHOLD', 'APPROVE_AML', 'CONFIGURE_AML', 'MONITOR_AML',
//    'GENERATE_AML_REPORT', 'SUSPEND_AML_TRANSACTION', 'MONITOR_LOAN_REPAYMENT_AML',
   
//    -- Risk Management
//    'VIEW_RISK_REPORT', 'MANAGE_RISK_SETTINGS', 'ASSESS_LOAN_REPAYMENT_RISK',
   
//    -- Reconciliation
//    'PROCESS_RECONCILIATION', 'VIEW_RECONCILIATION_REPORT', 'RECONCILE_LOAN_REPAYMENTS',
   
//    -- Product Management
//    'VIEW_PRODUCT', 'SETUP_PRODUCT', 'SETUP_LOAN_PRODUCT', 'MANAGE_PRODUCT_MAPPING',
   
//    -- Rate Management
//    'SETUP_LOAN_INTEREST', 'SETUP_DEPOSIT_INTEREST', 'SETUP_INDEX_RATE',
//    'SETUP_LOAN_PENALTY_RATE',
   
//    -- Business Unit
//    'CREATE_BUSINESS_UNIT', 'VIEW_BUSINESS_UNIT', 'MANAGE_SECURITY_BUSINESS_UNIT',
//    'MANAGE_BUSINESS_UNIT_ROLE',
   
//    -- Guarantor
//    'CREATE_GUARANTOR', 'VIEW_GUARANTOR', 'VIEW_GUARANTOR_DETAILS',
//    'UPDATE_GUARANTOR', 'DELETE_GUARANTOR', 'SEARCH_GUARANTOR', 'APPROVE_GUARANTOR',
//    'REJECT_GUARANTOR', 'VERIFY_GUARANTOR', 'REQUEST_GUARANTOR_REMOVAL',
//    'APPROVE_GUARANTOR_REMOVAL', 'REJECT_GUARANTOR_REMOVAL', 'REACTIVATE_GUARANTOR',
//    'DEACTIVATE_GUARANTOR', 'PERFORM_GUARANTOR_BULK_ACTIONS',
//    'VIEW_GUARANTOR_REPORTS', 'VIEW_GUARANTOR_DASHBOARD', 'VIEW_GUARANTOR_AUDIT_LOG',
//    'EXPORT_GUARANTOR_DATA',
   
//    -- Group
//    'GROUP.CREATE', 'GROUP.SAVINGS_MANAGEMENT', 'VIEW_GROUP', 'UPDATE_GROUP',
//    'DELETE_GROUP', 'MANAGE_GROUP_MEMBERS', 'APPROVE_GROUP', 'VIEW_GROUP_REPORTS',
//    'VIEW_GROUP_DASHBOARD', 'PERFORM_GROUP_BULK_ACTIONS',
   
//    -- Fixed Assets
//    'VIEW_FIXED_ASSET', 'REGISTER_ASSET', 'CALC_DEPRECIATION', 'DISPOSE_ASSET',
//    'TRANSFER_ASSET',
   
//    -- Thrift
//    'CREATE_THRIFT', 'COLLECT_THRIFT', 'WITHDRAWAL_THRIFT',
   
//    -- Standing Order
//    'CREATE_STANDING_ORDER', 'VIEW_STANDING_ORDER', 'UPDATE_STANDING_ORDER',
//    'DELETE_STANDING_ORDER',
   
//    -- Collection
//    'CREATE_COLLECTION', 'VIEW_COLLECTION', 'UPDATE_COLLECTION', 'DELETE_COLLECTION',
//    'PROCESS_COLLECTION', 'VERIFY_COLLECTION', 'APPROVE_COLLECTION', 'REJECT_COLLECTION',
//    'VIEW_COLLECTION_REPORTS', 'EXPORT_COLLECTION_DATA',
   
//    -- Loan Portfolio
//    'VIEW_LOAN_PORTFOLIO', 'MANAGE_LOAN_PORTFOLIO', 'UPDATE_LOAN_PORTFOLIO',
//    'VIEW_LOAN_PORTFOLIO_REPORTS', 'VIEW_LOAN_PORTFOLIO_ANALYTICS',
   
//    -- Dashboard
//    'VIEW_DASHBOARD', 'CUSTOMIZE_DASHBOARD', 'SHARE_DASHBOARD',
//    'VIEW_TELLER_DASHBOARD', 'VIEW_TRANSACTION_OVERVIEW', 'ACCESS_QUICK_ACTIONS',
//    'VIEW_REAL_TIME_STATS', 'VIEW_CREDIT_OFFICER_DASHBOARD',
//    'VIEW_MANAGER_DASHBOARD', 'VIEW_GUARANTOR_DASHBOARD', 'VIEW_BU_PERFORMANCE',
//    'DASHBOARD_REAL_TIME_STATS', 'VIEW_LOAN_REPAYMENT_STATS', 'VIEW_GROUP_LOAN_STATS',
   
//    -- Audit
//    'VIEW_AUDIT_LOGS', 'VIEW_TRANSACTION_AUDIT', 'VIEW_USER_AUDIT',
//    'VIEW_SYSTEM_AUDIT', 'EXPORT_AUDIT_LOGS', 'VIEW_LOAN_REPAYMENT_AUDIT',
//    'VIEW_GROUP_LOAN_AUDIT', 'VIEW_BULK_REPAYMENT_AUDIT',
   
//    -- Notifications
//    'VIEW_NOTIFICATIONS', 'MANAGE_NOTIFICATIONS', 'SEND_NOTIFICATIONS',
//    'CONFIGURE_NOTIFICATION_SETTINGS', 'SEND_LOAN_REPAYMENT_NOTIFICATIONS',
   
//    -- Agency Banking
//    'MANAGE_AGENCY_BANKING', 'VIEW_AGENCY_REPORT',
   
//    -- Mobile
//    'VIEW_MOBILE_APP', 'MANAGE_MOBILE_APP', 'APPROVE_MOBILE_TRANSACTIONS',
//    'PROCESS_MOBILE_LOAN_REPAYMENT',
   
//    -- Marketing
//    'CREATE_MARKETING_CAMPAIGN', 'VIEW_MARKETING_ANALYTICS',
   
//    -- Holiday
//    'MANAGE_HOLIDAY_CALENDAR',
   
//    -- Help & Support
//    'VIEW_HELP_DOCUMENTATION', 'CREATE_SUPPORT_TICKET', 'VIEW_SUPPORT_TICKETS',
//    'MANAGE_SUPPORT_TICKETS'
//  ), 1);

// -- 2. Branch Manager
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Branch Manager', 'MANAGER', 'Branch management and oversight',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_TRANSACTION_OVERVIEW', 'VIEW_MANAGER_DASHBOARD',
//    'ACCESS_QUICK_ACTIONS', 'VIEW_BU_PERFORMANCE', 'VIEW_LOAN_REPAYMENT_STATS',
//    'VIEW_GROUP_LOAN_STATS',
   
//    'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'CUSTOMER_APPROVAL',
//    'OPEN_ACCOUNT', 'FREEZE_ACCOUNT', 'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'VIEW_LOAN', 'APPROVE_LOAN', 'REJECT_LOAN',
//    'VIEW_LOAN_REPAYMENT_SCHEDULE', 'VIEW_REPAYMENT_HISTORY',
   
//    'VIEW_GROUP_LOAN', 'APPROVE_GROUP_LOAN',
   
//    'APPROVE_CUSTOMER_ACTION', 'APPROVE_STANDING_ORDER', 'APPROVE_VAULT_ACCESS',
//    'APPROVE_VAULT_OPERATION', 'APPROVE_LOAN_REPAYMENT', 'APPROVE_GROUP_LOAN',
//    'MANAGER_APPROVAL',
   
//    'VIEW_REPORTS', 'VIEW_PERFORMANCE_METRICS', 'VIEW_LOAN_REPAYMENT_REPORT',
//    'VIEW_GROUP_LOAN_REPORT',
   
//    'VIEW_VAULTS', 'VIEW_VAULT_STATUS', 'VIEW_VAULT_UTILIZATION',
//    'VIEW_BRANCH_VAULTS', 'VIEW_BRANCH_VAULT_STATUS', 'VIEW_VAULT_TRANSACTIONS',
//    'APPROVE_REQUEST', 'VIEW_PENDING_APPROVALS',
   
//    'VIEW_TELLER_PERFORMANCE', 'VIEW_BRANCH_PERFORMANCE',
   
//    'OPERATIONS_VIEW', 'OPERATIONS_APPROVE'
//  ), 1);

// -- 3. Teller
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Teller', 'TELLER', 'Daily banking operations',
//  JSON_ARRAY(
//    'VIEW_TELLER_DASHBOARD', 'VIEW_TRANSACTION_OVERVIEW', 'ACCESS_QUICK_ACTIONS',
//    'VIEW_REAL_TIME_STATS', 'DASHBOARD_REAL_TIME_STATS',
   
//    'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'VIEW_CUSTOMER_PROFILE',
//    'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
//    'DEPOSIT_101', 'WITHDRAWAL_102',
   
//    'MAKE_DEPOSIT', 'MAKE_WITHDRAWAL', 'INITIATE_TRANSFER',
//    'MAKE_OPENING_DEPOSIT', 'VIEW_RECENT_TRANSACTIONS', 'REPRINT_TRANSACTION_RECEIPT',
//    'PROCESS_LOAN_REPAYMENT_TRANSACTION',
   
//    'VIEW_TELLER_SUMMARY_REPORT',
   
//    'COLLECT_LOAN', 'PROCESS_MANUAL_LOAN_REPAYMENT',
//    'MANUAL_LOAN_REPAYMENT', 'PROCESS_LOAN_REPAYMENT', 'PRINT_REPAYMENT_RECEIPT',
   
//    'WITHDRAWAL_THRIFT',
   
//    'VIEW_DRAWER', 'MANAGE_DRAWER', 'RECONCILE_DRAWER',
//    'PRINT_RECEIPT',
   
//    'VIEW_TELLER_PERFORMANCE', 'VIEW_LOAN_REPAYMENT_PERFORMANCE'
//  ), 1);

// -- 4. Customer Service Officer (CSO)
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Customer Service Officer', 'CSO', 'Customer support and account management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_CREDIT_OFFICER_DASHBOARD',
   
//    'CREATE_CUSTOMER', 'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'VERIFY_KYC',
//    'CUSTOMER_IDENTIFICATION', 'VIEW_CUSTOMER_PROFILE', 'CUSTOMER_APPROVAL',
   
//    'OPEN_ACCOUNT', 'FREEZE_ACCOUNT', 'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'VIEW_LOAN', 'PROCESS_LOAN', 'CREATE_LOAN_CREDIT_APPLICATION',
//    'VIEW_LOAN_REPAYMENT_SCHEDULE', 'VIEW_REPAYMENT_HISTORY',
   
//    'VIEW_LOAN_FEES', 'CREATE_LOAN_FEE', 'UPDATE_LOAN_FEE',
//    'TOGGLE_LOAN_FEE_STATUS',
   
//    'CREATE_CREDIT_APP', 'REVIEW_CREDIT_APP',
   
//    'VIEW_REPORTS', 'VIEW_CUSTOMER_REPORT',
   
//    'CREATE_GUARANTOR', 'VIEW_GUARANTOR', 'UPDATE_GUARANTOR', 'SEARCH_GUARANTOR',
//    'VERIFY_GUARANTOR',
   
//    'CREATE_STANDING_ORDER', 'VIEW_STANDING_ORDER', 'UPDATE_STANDING_ORDER',
   
//    'CREATE_COLLECTION', 'VIEW_COLLECTION', 'PROCESS_COLLECTION',
   
//    'VIEW_PRODUCT', 'SETUP_LOAN_PRODUCT',
   
//    'ACCESS_VAULT_TRAINING', 'VIEW_VAULT_DOCUMENTATION'
//  ), 1);

// -- 5. Loan Officer
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Loan Officer', 'LOAN_OFFICER', 'Loan processing and underwriting',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_CREDIT_OFFICER_DASHBOARD',
   
//    'CREATE_CUSTOMER', 'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'VERIFY_KYC',
   
//    'OPEN_ACCOUNT', 'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'CREATE_LOAN_CREDIT_APPLICATION', 'VIEW_LOAN', 'PROCESS_LOAN',
//    'DISBURSE_LOAN', 'COLLECT_LOAN', 'RECOVER_LOAN', 'CREATE_LOAN_CONTRACT',
//    'PROCESS_MANUAL_LOAN_REPAYMENT', 'PROCESS_BULK_LOAN_REPAYMENTS',
   
//    'MANUAL_LOAN_REPAYMENT', 'PROCESS_LOAN_REPAYMENT',
//    'VIEW_LOAN_REPAYMENT_SCHEDULE', 'PROCESS_PARTIAL_REPAYMENT',
//    'PROCESS_ADVANCE_REPAYMENT', 'RESCHEDULE_REPAYMENT',
//    'VIEW_REPAYMENT_HISTORY', 'PRINT_REPAYMENT_RECEIPT', 'RECONCILE_REPAYMENT',
   
//    'CREATE_GROUP_LOAN', 'VIEW_GROUP_LOAN', 'UPDATE_GROUP_LOAN',
//    'DISBURSE_GROUP_LOAN', 'PROCESS_GROUP_LOAN_REPAYMENT',
//    'VIEW_GROUP_LOAN_SCHEDULE', 'PROCESS_BULK_GROUP_LOAN_REPAYMENT',
//    'COLLECT_GROUP_SAVINGS',
   
//    'VIEW_LOAN_FEES', 'CREATE_LOAN_FEE', 'UPDATE_LOAN_FEE',
   
//    'CREATE_CREDIT_APP', 'REVIEW_CREDIT_APP', 'APPROVE_CREDIT_APP',
   
//    'VIEW_REPORTS', 'VIEW_LOAN_REPAYMENT_REPORT', 'VIEW_GROUP_LOAN_REPORT',
   
//    'CREATE_GUARANTOR', 'VIEW_GUARANTOR', 'UPDATE_GUARANTOR', 'VERIFY_GUARANTOR',
   
//    'CREATE_COLLECTION', 'VIEW_COLLECTION', 'PROCESS_COLLECTION',
   
//    'VIEW_LOAN_PORTFOLIO', 'VIEW_LOAN_PORTFOLIO_REPORTS',
   
//    'SETUP_LOAN_INTEREST', 'SETUP_LOAN_PENALTY_RATE',
   
//    'PROCESS_BULK_OPERATIONS', 'VALIDATE_BULK_DATA', 'EXECUTE_BULK_OPERATIONS',
   
//    'VIEW_PERFORMANCE_METRICS', 'VIEW_LOAN_REPAYMENT_PERFORMANCE'
//  ), 1);

// -- 6. Auditor
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Auditor', 'AUDITOR', 'View-only access for auditing',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD',
   
//    'VIEW_CUSTOMER', 'VIEW_CUSTOMER_PROFILE',
//    'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'VIEW_LOAN', 'VIEW_REPAYMENT_HISTORY', 'VIEW_LOAN_REPAYMENT_SCHEDULE',
   
//    'VIEW_TRANSACTION_HISTORY', 'VIEW_RECENT_TRANSACTIONS', 'VIEW_TRANSACTION_STATS',
   
//    'VIEW_REPORTS', 'VIEW_ALL_REPORTS', 'VIEW_CUSTOMER_REPORT',
//    'VIEW_ACCOUNT_STATEMENT_REPORT', 'VIEW_TRIAL_BALANCE_REPORT',
//    'VIEW_INCOME_EXPENSE_REPORT', 'VIEW_LOAN_REPAYMENT_REPORT',
//    'VIEW_GROUP_LOAN_REPORT', 'EXPORT_REPORTS',
   
//    'VIEW_VAULTS', 'VIEW_VAULT_STATUS', 'VIEW_VAULT_TRANSACTIONS',
//    'VIEW_VAULT_UTILIZATION', 'VIEW_SECURITY_COMPLIANCE', 'VIEW_VAULT_STATISTICS',
//    'VIEW_AUDIT_TRAIL', 'VIEW_BRANCH_VAULTS', 'GENERATE_VAULT_REPORT',
//    'CONDUCT_VAULT_AUDIT', 'PERFORM_VAULT_COMPLIANCE_CHECK',
   
//    'VIEW_AUDIT_LOGS', 'VIEW_TRANSACTION_AUDIT', 'VIEW_USER_AUDIT',
//    'VIEW_SYSTEM_AUDIT', 'EXPORT_AUDIT_LOGS', 'VIEW_LOAN_REPAYMENT_AUDIT',
//    'VIEW_GROUP_LOAN_AUDIT', 'VIEW_BULK_REPAYMENT_AUDIT',
   
//    'VIEW_RISK_REPORT', 'VIEW_AML_THRESHOLD',
   
//    'VIEW_GROUP', 'VIEW_GROUP_REPORTS', 'VIEW_GROUP_DASHBOARD',
   
//    'VIEW_GUARANTOR', 'VIEW_GUARANTOR_DETAILS', 'VIEW_GUARANTOR_AUDIT_LOG',
   
//    'VIEW_COLLECTION', 'VIEW_COLLECTION_REPORTS'
//  ), 1);

// -- 7. IT Administrator
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('IT Administrator', 'IT_ADMIN', 'System administration and user management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD',
   
//    'MANAGE_USERS', 'CREATE_USER', 'UPDATE_USER', 'VIEW_USERS', 'DELETE_USER',
//    'ACTIVATE_USER', 'DEACTIVATE_USER', 'RESET_USER_PASSWORD',
//    'ASSIGN_USER_ROLES', 'VIEW_USER_PROFILE', 'EXPORT_USER_DATA',
   
//    'MANAGE_USERS_MODULE', 'MANAGE_SYSTEM_CONFIG', 'VIEW_AUDIT_LOGS',
//    'SYSTEM_BACKUP', 'SYSTEM_RESTORE', 'VIEW_SYSTEM_DATE',
//    'TRIGGER_OS_OPERATIONS', 'VIEW_LICENSE_DETAILS', 'CONFIGURE_LOAN_REPAYMENT',
   
//    'CREATE_PERMISSION', 'VIEW_PERMISSIONS', 'UPDATE_PERMISSIONS', 'ASSIGN_ROLES',
//    'CLONE_ROLE_PERMISSIONS', 'MANAGE_BUSINESS_ROLE', 'CREATE_BUSINESS_ROLE',
//    'VIEW_BUSINESS_ROLE_QUEUE', 'SETUP_BUSINESS_ROLE_QUEUE',
   
//    'ADD_USER', 'ASSIGN_USER_ROLE', 'VIEW_SECURITY_CONSOLE',
   
//    'VIEW_VAULT_CONFIG', 'CONFIGURE_VAULT', 'MANAGE_VAULT_ACCESS',
//    'UPDATE_SECURITY_FEATURES', 'CONFIGURE_VAULT_ALERTS', 'UPDATE_VAULT_DOCUMENTATION',
//    'VIEW_VAULT_POLICIES', 'CERTIFY_VAULT_PERSONNEL', 'VIEW_VAULT_CERTIFICATIONS',
   
//    'VIEW_BUSINESS_UNIT', 'MANAGE_BUSINESS_UNIT_ROLE',
   
//    'VIEW_QUEUE', 'MANAGE_QUEUE', 'CLEAR_QUEUE',
//    'MANAGE_LOAN_REPAYMENT_QUEUE', 'MANAGE_BULK_REPAYMENT_QUEUE',
   
//    'CONFIGURE_WORKFLOW', 'MANAGE_WORKFLOW_SUBPROCESS',
   
//    'VIEW_SYSTEM_HEALTH', 'VIEW_REAL_TIME_STATISTICS',
   
//    'VIEW_HELP_DOCUMENTATION', 'CREATE_SUPPORT_TICKET', 'VIEW_SUPPORT_TICKETS',
//    'MANAGE_SUPPORT_TICKETS'
//  ), 1);

// -- 8. Accountant
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Accountant', 'ACCOUNTANT', 'Financial accounting and reconciliation',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD', 'VIEW_BU_PERFORMANCE',
   
//    'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'CUSTOMER_POSTING', 'GL_POSTING', 'REVERSE_TRANSACTION', 'ADJUST_TRANSACTION',
//    'VIEW_CHART_OF_ACCOUNT', 'VIEW_GL_SUBFOLDER', 'VIEW_SUBFOLDER_ACCOUNT',
//    'MANAGE_DEPARTMENT',
   
//    'PROCESS_GL_TO_GL', 'PROCESS_CREDIT_GL', 'PROCESS_DEBIT_GL',
   
//    'VIEW_REPORTS', 'VIEW_TRIAL_BALANCE_REPORT', 'VIEW_INCOME_EXPENSE_REPORT',
//    'VIEW_FINANCIAL_STATISTICS', 'EXPORT_REPORTS', 'GENERATE_REPORTS',
   
//    'VIEW_VAULT_RECONCILIATION', 'VAULT_RECONCILIATION', 'VIEW_VAULT_TRANSACTIONS',
//    'EXPORT_VAULT_TRANSACTIONS',
   
//    'PROCESS_RECONCILIATION', 'VIEW_RECONCILIATION_REPORT',
//    'RECONCILE_LOAN_REPAYMENTS',
   
//    'VIEW_FIXED_ASSET', 'CALC_DEPRECIATION',
   
//    'TREASURY_VIEW', 'TREASURY_APPROVE',
   
//    'VIEW_LOAN_PORTFOLIO', 'VIEW_LOAN_PORTFOLIO_REPORTS',
//    'VIEW_LOAN_PORTFOLIO_ANALYTICS',
   
//    'EXPORT_PERFORMANCE_DATA'
//  ), 1);

// -- 9. Compliance Officer
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Compliance Officer', 'COMPLIANCE', 'Regulatory compliance monitoring',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD',
   
//    'VIEW_CUSTOMER', 'VIEW_CUSTOMER_PROFILE', 'VERIFY_KYC',
//    'CUSTOMER_IDENTIFICATION',
   
//    'VIEW_TRANSACTION_HISTORY', 'VIEW_TRANSACTION_STATS',
   
//    'VIEW_REPORTS', 'VIEW_ALL_REPORTS', 'VIEW_CUSTOMER_REPORT',
//    'VIEW_LOAN_REPAYMENT_REPORT', 'EXPORT_REPORTS',
   
//    'VIEW_AUDIT_LOGS', 'VIEW_TRANSACTION_AUDIT', 'VIEW_USER_AUDIT',
//    'VIEW_SYSTEM_AUDIT', 'EXPORT_AUDIT_LOGS',
//    'VIEW_LOAN_REPAYMENT_AUDIT', 'VIEW_GROUP_LOAN_AUDIT',
//    'VIEW_BULK_REPAYMENT_AUDIT',
   
//    'VIEW_AML_THRESHOLD', 'APPROVE_AML', 'CONFIGURE_AML', 'MONITOR_AML',
//    'GENERATE_AML_REPORT', 'SUSPEND_AML_TRANSACTION',
//    'MONITOR_LOAN_REPAYMENT_AML',
   
//    'VIEW_RISK_REPORT', 'MANAGE_RISK_SETTINGS', 'ASSESS_LOAN_REPAYMENT_RISK',
   
//    'VIEW_VAULTS', 'VIEW_VAULT_UTILIZATION', 'VIEW_SECURITY_COMPLIANCE',
//    'VIEW_VAULT_STATISTICS', 'VIEW_AUDIT_TRAIL', 'CONDUCT_VAULT_AUDIT',
//    'PERFORM_VAULT_COMPLIANCE_CHECK',
   
//    'VIEW_BRANCH_VAULTS', 'VIEW_BRANCH_VAULT_STATUS',
   
//    'VIEW_GUARANTOR', 'VIEW_GUARANTOR_AUDIT_LOG',
   
//    'VIEW_GROUP_LOAN_AUDIT'
//  ), 1);

// -- 10. Head of Credit
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Head of Credit', 'HEAD_CREDIT', 'Credit policy and portfolio management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD', 'VIEW_BU_PERFORMANCE',
   
//    'VIEW_CUSTOMER', 'VIEW_CUSTOMER_PROFILE',
//    'VIEW_ACCOUNT_BALANCE',
   
//    'VIEW_LOAN', 'APPROVE_LOAN', 'REJECT_LOAN', 'RESTRUCTURE_LOAN',
//    'WRITE_OFF_LOAN', 'RECOVER_LOAN',
   
//    'VIEW_LOAN_REPAYMENT_SCHEDULE', 'VIEW_REPAYMENT_HISTORY',
//    'OVERRIDE_LOAN_REPAYMENT', 'RESCHEDULE_REPAYMENT', 'REVERSE_LOAN_REPAYMENT',
//    'RECONCILE_REPAYMENT',
   
//    'VIEW_GROUP_LOAN', 'APPROVE_GROUP_LOAN', 'PROCESS_BULK_GROUP_LOAN_REPAYMENT',
   
//    'APPROVE_LOAN_REPAYMENT', 'APPROVE_GROUP_LOAN', 'APPROVE_BULK_REPAYMENT',
   
//    'VIEW_REPORTS', 'VIEW_PERFORMANCE_METRICS', 'VIEW_LOAN_REPAYMENT_REPORT',
//    'VIEW_GROUP_LOAN_REPORT', 'VIEW_BULK_REPAYMENT_REPORT',
   
//    'VIEW_LOAN_PORTFOLIO', 'MANAGE_LOAN_PORTFOLIO', 'UPDATE_LOAN_PORTFOLIO',
//    'VIEW_LOAN_PORTFOLIO_REPORTS', 'VIEW_LOAN_PORTFOLIO_ANALYTICS',
   
//    'SETUP_LOAN_INTEREST', 'SETUP_LOAN_PENALTY_RATE',
//    'SETUP_INDEX_RATE',
   
//    'VIEW_LOAN_REPAYMENT_PERFORMANCE',
   
//    'ASSESS_LOAN_REPAYMENT_RISK',
   
//    'APPROVE_CREDIT_APP', 'REVIEW_CREDIT_APP',
   
//    'VIEW_RISK_REPORT'
//  ), 1);

// -- 11. Human Resources
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Human Resources', 'HR', 'Employee and payroll management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD',
   
//    'MANAGE_USERS', 'CREATE_USER', 'UPDATE_USER', 'VIEW_USERS',
//    'ACTIVATE_USER', 'DEACTIVATE_USER', 'RESET_USER_PASSWORD',
//    'ASSIGN_USER_ROLES', 'VIEW_USER_PROFILE', 'EXPORT_USER_DATA',
   
//    'VIEW_REPORTS', 'VIEW_PERFORMANCE_METRICS', 'VIEW_TELLER_PERFORMANCE',
//    'VIEW_BRANCH_PERFORMANCE',
   
//    'VIEW_AUDIT_LOGS', 'VIEW_USER_AUDIT',
   
//    'VIEW_NOTIFICATIONS', 'SEND_NOTIFICATIONS',
   
//    'VIEW_HELP_DOCUMENTATION', 'CREATE_SUPPORT_TICKET', 'VIEW_SUPPORT_TICKETS'
//  ), 1);

// -- 12. Relationship Manager
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Relationship Manager', 'RELATIONSHIP', 'Customer relationship management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_BU_PERFORMANCE',
   
//    'CREATE_CUSTOMER', 'VIEW_CUSTOMER', 'UPDATE_CUSTOMER', 'VIEW_CUSTOMER_PROFILE',
//    'VERIFY_KYC', 'CUSTOMER_APPROVAL',
   
//    'OPEN_ACCOUNT', 'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'VIEW_LOAN', 'CREATE_LOAN_CREDIT_APPLICATION',
//    'VIEW_LOAN_REPAYMENT_SCHEDULE', 'VIEW_REPAYMENT_HISTORY',
   
//    'VIEW_REPORTS', 'VIEW_CUSTOMER_REPORT', 'VIEW_PERFORMANCE_METRICS',
   
//    'VIEW_NOTIFICATIONS', 'SEND_NOTIFICATIONS',
//    'SEND_LOAN_REPAYMENT_NOTIFICATIONS',
   
//    'VIEW_MOBILE_APP', 'MANAGE_MOBILE_APP',
   
//    'CREATE_MARKETING_CAMPAIGN', 'VIEW_MARKETING_ANALYTICS',
   
//    'VIEW_BUSINESS_ANALYTICS', 'EXPORT_ANALYTICS_DATA'
//  ), 1);

// -- 13. Marketing Officer
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Marketing Officer', 'MARKETING', 'Marketing campaign management',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD',
   
//    'VIEW_CUSTOMER', 'VIEW_CUSTOMER_PROFILE', 'VIEW_CUSTOMER_SEGMENTS',
   
//    'VIEW_REPORTS', 'VIEW_PERFORMANCE_METRICS', 'VIEW_CUSTOMER_REPORT',
//    'EXPORT_REPORTS',
   
//    'CREATE_MARKETING_CAMPAIGN', 'VIEW_MARKETING_ANALYTICS',
   
//    'VIEW_NOTIFICATIONS', 'SEND_NOTIFICATIONS',
   
//    'VIEW_BUSINESS_ANALYTICS', 'EXPORT_ANALYTICS_DATA',
   
//    'EXPORT_CUSTOMER_DATA',
   
//    'VIEW_MOBILE_APP'
//  ), 1);

// -- 14. Internal Control Officer
// INSERT INTO roles (role_name, code, description, permissions, active) VALUES
// ('Internal Control Officer', 'INTERNAL_CONTROL', 'Internal control monitoring',
//  JSON_ARRAY(
//    'VIEW_DASHBOARD', 'VIEW_MANAGER_DASHBOARD',
   
//    'VIEW_CUSTOMER', 'VIEW_CUSTOMER_PROFILE',
//    'VIEW_ACCOUNT_BALANCE', 'VIEW_ACCOUNT_STATEMENT',
   
//    'VIEW_TRANSACTION_HISTORY', 'VIEW_TRANSACTION_STATS',
   
//    'VIEW_REPORTS', 'VIEW_ALL_REPORTS', 'VIEW_AUDIT_LOGS',
//    'VIEW_TRANSACTION_AUDIT', 'VIEW_USER_AUDIT', 'VIEW_SYSTEM_AUDIT',
   
//    'VIEW_VAULTS', 'VIEW_VAULT_UTILIZATION', 'VIEW_SECURITY_COMPLIANCE',
//    'VIEW_VAULT_STATISTICS', 'VIEW_AUDIT_TRAIL', 'VIEW_VAULT_CONTROL',
   
//    'VIEW_RISK_REPORT', 'VIEW_AML_THRESHOLD',
   
//    'VIEW_GROUP', 'VIEW_GROUP_REPORTS',
   
//    'VIEW_COLLECTION', 'VIEW_COLLECTION_REPORTS'
//  ), 1);

// -- ============================================
// -- VERIFY ALL ROLES
// -- ============================================

// -- Count total roles
// SELECT COUNT(*) AS total_roles FROM roles;

// -- View all roles summary
// SELECT 
//     role_id, 
//     role_name, 
//     code, 
//     active,
//     JSON_LENGTH(permissions) AS permission_count,
//     LEFT(description, 50) AS short_description
// FROM roles 
// ORDER BY role_id;

// -- View permissions for a specific role (example: Administrator)
// SELECT 
//     role_name,
//     JSON_PRETTY(permissions) AS permissions
// FROM roles 
// WHERE code = 'ADMIN';

// -- View active roles only
// SELECT role_id, role_name, code 
// FROM roles 
// WHERE active = 1 
// ORDER BY role_name;