import mongoose from 'mongoose';
import DepositTransaction from './DepositTransaction.js';  // Import the transaction model

const DepositAccountSummarySchema = new mongoose.Schema({
  ACCT_ID: { type: Number, required: true },
  ACCT_NO: { type: Number, maxlength: 60 },
  LEDGER_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CLEARED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  UNCLEARED1_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  UNCLEARED2_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  RESERVED_FUND: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  EARMARKED_FUND: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_INT_ACCRUED: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_ACCRUED: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  LAST_ACTIVITY_DT: { type: Date },
  LAST_DEPOSIT_DT: { type: Date },
  LAST_DEPOSIT_AMT: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  LAST_WITHDRAWL_DT: { type: Date },
  LAST_WITHDRAWL_AMT: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  LAST_OD_DT: { type: Date },
  DR_INT_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_BAL_FWD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_BAL_FWD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  LEDGER_BAL_FWD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CLEARED_BAL_FWD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_TURNOVER: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_TURNOVER: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CHQ_COUNT: { type: Number, default: 0 },
  MIN_LEDGER_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  MIN_CLEARED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  MAX_LEDGER_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  MAX_CLEARED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  AVG_LEDGER_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  AVG_CLEARED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  AVG_LEDGER_BAL_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  AVG_CLEARED_BAL_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_COUNT: { type: Number, default: 0 },
  CR_COUNT: { type: Number, default: 0 },
  REC_ST: { type: String, maxlength: 1 },
  VERSION_NO: { type: Number },
  ROW_TS: { type: Date },
  USER_ID: { type: String, maxlength: 24 },
  CREATE_DT: { type: Date },
  SYS_CREATE_TS: { type: Date },
  CREATED_BY: { type: String, maxlength: 24 },
  ACCT_CYCLE_START_DT: { type: Date },
  MAX_LEDGER_BAL_DT: { type: Date },
  MAX_CLEARED_BAL_DT: { type: Date },
  MIN_LEDGER_BAL_DT: { type: Date },
  MIN_CLEARED_BAL_DT: { type: Date },
  AVG_BAL_DT: { type: Date },
  CHRG_APPLIED: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_PAID: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_INT_CHRGD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  TOTAL_COST: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  TOTAL_CHRGS: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  TOTAL_TAX: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_PENDING_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_PENDING_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  ACCT_CYCLE_END_DT: { type: Date },
  PROD_ID: { type: Number },
  DR_INT_REMAINDER_ACCRUED: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_REMAINDER_ACCRUED: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_INT_REMAINDER_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_REMAINDER_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  YTD_RETURNS_COUNT: { type: Number, default: 0 },
  YTD_CLEARING_RETURNS_COUNT: { type: Number, default: 0 },
  STAT_UPD_FG: { type: String, maxlength: 1 },
  TEMP_RECLASSIFICATION_ST: { type: String, maxlength: 1 },
  LAST_ACCRUAL_TIME: { type: Date },
  DR_INT_ACCRUED_PTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_ACCRUED_PTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CUMULATIVE_LIEN_AMT: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  ACCRUAL_DUE_FG: { type: String, maxlength: 1 },
  LAST_PROD_UPD_DT: { type: Date },
  EARLIEST_BACKVALUE_DT: { type: Date },
  LAST_BACKVALUE_DT: { type: Date },
  ACCT_CYCLE_OPENING_LED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  ACCT_CYCLE_OPENING_CLR_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  ACCT_CYCLE_CLOSING_LED_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  ACCT_CYCLE_CLOSING_CLR_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  STMNT_START_DT: { type: Date },
  NEXT_STMNT_DT: { type: Date },
  STMNT_COUNT: { type: Number, default: 0 },
  STMNT_OPENNING_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  PROVISION_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CURRENT_ACCRUAL_DT: { type: Date },
  PREPAID_CHRG_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_CALCULATED_EFF_INT_RATE: { type: mongoose.Schema.Types.Decimal128, precision: 12 },
  DR_CALCULATED_EFF_INT_RATE: { type: mongoose.Schema.Types.Decimal128, precision: 12 },
  DR_LAST_ACCRUAL_DT: { type: Date },
  DR_NEXT_ACCRUAL_DT: { type: Date },
  CR_LAST_ACCRUAL_DT: { type: Date },
  CR_NEXT_ACCRUAL_DT: { type: Date },
  DR_INT_OVR_FG: { type: String, maxlength: 1 },
  CR_INT_OVR_FG: { type: String, maxlength: 1 },
  DR_INT_ACCRUED_YTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_INT_ACCRUED_LTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_ACCRUED_YTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  CR_INT_ACCRUED_LTD: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DR_LAST_BACKDATED_TXN_DT: { type: Date },
  CR_LAST_BACKDATED_TXN_DT: { type: Date },
  DR_INT_PAID: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  BAL_CHNG_FG: { type: String, maxlength: 1 },
  PENAL_BAL: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  PENAL_EFFECTIVE_RATE: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  PENAL_INT_PER_DAY: { type: mongoose.Schema.Types.Decimal128, default: 0 },
  DELINQUENT_DT: { type: Date },
  LAST_PROV_DT: { type: Date },
  
  // Embed transaction history
  transactions: [{ type: mongoose.Schema.Types.ObjectId, ref: 'DepositTransaction' }],
});

export default mongoose.model('DepositAccountSummary', DepositAccountSummarySchema);
