// models/AuditTrail.js
import mongoose from 'mongoose';

export const auditTrailSchema = new mongoose.Schema({  // Fixed: changed "onst" to "const"
  // ID Fields
  event_id: {
    type: Number,
    unique: true,
    required: false // Will be generated by generateEventID()
  },
  _id: {
    type: mongoose.Schema.Types.ObjectId,
    default: () => new mongoose.Types.ObjectId()
  },
  
  // User/Entity References
  user_id: {
    type: String,
    ref: 'User',
    required: true,
    alias: 'USER_ID' // Allows both user_id and USER_ID to work
  },
  
  // Event Information
  event_type: {
    type: String,
    required: true,
    alias: 'EVENT_TYPE' // Supports both event_type and EVENT_TYPE
  },
  action: {
    type: String,
    required: true,
    alias: 'ACTION' // Supports both action and ACTION
  },
  
  // Data Values
  old_value: {
    type: mongoose.Schema.Types.Mixed,
    default: null,
    alias: 'OLD_VALUE'
  },
  new_value: {
    type: mongoose.Schema.Types.Mixed,
    required: true,
    alias: 'NEW_VALUE'
  },
  
  // Technical Fields
  ip_address: {
    type: String,
    required: true,
    alias: 'ipAddress' // Supports both ip_address and ipAddress
  },
  timestamp: {
    type: Date,
    default: Date.now,
    required: true
  },
  
  // Additional Fields
  entity_type: String, // For tracking which entity was modified
  entity_id: mongoose.Schema.Types.ObjectId, // ID of the modified entity
  status: String, // SUCCESS, FAILED, etc.
  additional_info: mongoose.Schema.Types.Mixed // Any extra metadata
}, {
  collection: 'audit_trail',
  timestamps: true, // Adds createdAt and updatedAt
  versionKey: false, // Disables the __v field
  toJSON: { virtuals: true, getters: true },
  toObject: { virtuals: true, getters: true }
});

// Add index for better query performance
auditTrailSchema.index({ event_id: 1 });
auditTrailSchema.index({ user_id: 1 });
auditTrailSchema.index({ event_type: 1 });
auditTrailSchema.index({ timestamp: -1 });

const AuditTrail = mongoose.model('AuditTrail', auditTrailSchema);

export default AuditTrail;