import mongoose from 'mongoose';

const PermissionsSchema = new mongoose.Schema({
  BU_ROLE_ID: {
    type: Number,
    required: true
  },
  DRAWER_ACCESS_LEVEL: { type: [String], default: [] }, // Change to array of strings
  CUST_POSTING_ACCESS_LEVEL: { type: [String], default: [] },
  GL_POSTING_ACCESS_LEVEL: { type: [String], default: [] },
  TXN_ENQUIRY_ACCESS_LVL: { type: [String], default: [] },
  FIXED_ASSET_ACCESS_LEVEL: { type: [String], default: [] },
  REPORT_ACCESS_LEVEL: { type: [String], default: [] },
  DASHBOARD_ACCESS_LEVEL: { type: [String], default: [] },
  CREDIT_APPL_ACCESS_LEVEL: { type: [String], default: [] },
  CUSTOMER_ACCESS_LEVEL: { type: [String], default: [] },
  ACCOUNT_ACCESS_LEVEL: { type: [String], default: [] }
}, { timestamps: true });

const Permissions = mongoose.model('Permissions', PermissionsSchema);



// Define user roles with permissions
const userRoles = [
  {
    id: 1,
    name: "Administrator",
    permissions: new Permissions({
      canCreateUser: true,
      canDeleteUser: true,
      canViewReports: true,
      canAccessVault: false,
      canManageTransactions: true,
       DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
    })
  },
  {
    id: 2,
    name: "Head Banking Services",
    permissions: new Permissions({
      DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
    })
  },
    {
  id: 3,
  name: "Loan Processing Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 4,
  name: "Senior Financial Accountant",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 5,
  name: "Internal Control Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 6,
  name: "Internal Control Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 7,
  name: "Head of Credit",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 8,
  name: "Internal Audit Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 9,
  name: "Head Human Resources",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 10,
  name: "Human Resource Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 11,
  name: "IT Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 12,
  name: "Financial Accountant",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 13,
  name: "Financial Accountant Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 14,
  name: "Chief Financial Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 15,
  name: "Chief Executive Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 16,
  name: "Treasurer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 17,
  name: "Loan Processing Supervisor",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 18,
  name: "Senior Financial Accountant",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 19,
  name: "Branch Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 20,
  name: "Branch Operation Supervisor",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 21,
  name: "Chief Operation Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 22,
  name: "Marketing Manager",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 23,
  name: "Payment and Reconciliation USD",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 24,
  name: "EOD Operator",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 25,
  name: "Recovery Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 26,
  name: "Relationship Development Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 27,
  name: "Customer Relationship Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 28,
  name: "Customer Service Officer",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 29,
  name: "Teller",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 30,
  name: "Head Teller",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 31,
  name: "Customer Relationship Supervisor",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 32,
  name: "Recovery Team Lead",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 32,
  name: "Business Analyst",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 33,
  name: "Credit Risk Analyst",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 34,
  name: "Head of Digital Banking",
  permissions: new Permissions({
    DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
    ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 35,
  name: "Agency Banking Officer",
  permissions: new Permissions({
      DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
{
  id: 36,
  name: "Channel Manager",
  permissions: new Permissions({
      DRAWER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUST_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      GL_POSTING_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      TXN_ENQUIRY_ACCESS_LVL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      FIXED_ASSET_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      REPORT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      DASHBOARD_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CREDIT_APPL_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      CUSTOMER_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE'],
      ACCOUNT_ACCESS_LEVEL: ['ALL BUSINESS UNIT', 'OWN BUSINESS UNIT', 'PARENT BUSINESS UNIT STRUCTURE']
  })
},
// Add other roles similarly...
];


async function saveUserRoles(USER_ID) {
  for (const role of userRoles) {
    const permissions = new Permissions(role.permissions); // Create permissions from the role
    await permissions.save(); // Save permissions to the database

    const userRole = new UserRole({
      USER_ROLE_ID: role.id,
      SYSUSER_ID: 1, // Replace with actual SYSUSER_ID
      BU_ROLE_ID: 1, // Replace with actual BU_ROLE_ID
      USER_ID: USER_ID, // Pass the actual USER_ID dynamically
      CREATED_BY: 'administrator', // Replace with the creator's username or ID
      permissions: permissions._id, // Save the permissions reference
      EFF_FROM_DT: new Date(), // Add this field if needed
      EFF_TO_DT: null, // Default to null for ongoing roles
      DEF_ROLE_FG: 'N', // Default to 'N' or another value as needed
      SUPERVISOR_FG: 'N', // Default to 'N'
      MULTI_CRNCY_FG: 'N', // Default to 'N'
      // Include other fields if necessary
    });
    await userRole.save(); // Save the userRole to the database
  }
}


export default Permissions;
